<% 
	strConnect = strConnect&"Provider=SQLOLEDB.1;Persist Security Info=True;"
	strConnect = strConnect&"Data Source=115.68.112.26;"  
	strConnect = strConnect&"User ID=sportsdiary;"             
	strConnect = strConnect&"Password=dnlemfkdls715)@*@;"             
	strConnect = strConnect&"Initial Catalog=sportsdiary;"   
	
	
	strConnect2 = strConnect2&"Provider=SQLOLEDB.1;Persist Security Info=True;"
	strConnect2 = strConnect2&"Data Source=db.itemcenter.co.kr;"  
	strConnect2 = strConnect2&"User ID=widsql;"             
	strConnect2 = strConnect2&"Password=ic%^&1058!@#;" 
	strConnect2 = strConnect2&"Initial Catalog=ITEMCENTER;"   
%>