
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="author" content="Windows 사용자" />
    <meta name="company" content="Microsoft Corporation" />
    <title>배드민턴 경기기록지</title>
  <style type="text/css">
    html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
    table { border-collapse:collapse; page-break-after:always }
    .gridlines td { border:1px dotted black }
    .gridlines th { border:1px dotted black }
    .b { text-align:center }
    .e { text-align:center }
    .f { text-align:right }
    .inlineStr { text-align:left }
    .n { text-align:right }
    .s { text-align:left }
    td.style0 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style0 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style1 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style1 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style2 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    th.style2 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    td.style3 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    th.style3 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    td.style4 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:20pt; background-color:white }
    th.style4 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:20pt; background-color:white }
    td.style5 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:20pt; background-color:white }
    th.style5 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:20pt; background-color:white }
    td.style6 { vertical-align:middle; text-align:center; /*border-bottom:2px solid #000000 !important;*/ border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style6 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style7 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; /*border-right:2px solid #000000 !important;*/ color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style7 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; /*border-right:2px solid #000000 !important;*/ color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style8 { vertical-align:middle; text-align:center; /*border-bottom:2px solid #000000 !important;*/ border-top:none #000000; border-left:none #000000; /*border-right:2px solid #000000 !important;*/ color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style8 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; /*border-right:2px solid #000000 !important;*/ color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style9 { vertical-align:bottom; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    th.style9 { vertical-align:bottom; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    td.style10 { vertical-align:bottom; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    th.style10 { vertical-align:bottom; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    td.style11 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    th.style11 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    td.style12 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:24pt; background-color:white }
    th.style12 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:24pt; background-color:white }
    td.style13 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:24pt; background-color:white }
    th.style13 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:24pt; background-color:white }
    td.style14 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    th.style14 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    td.style15 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:28pt; background-color:white }
    th.style15 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:28pt; background-color:white }
    td.style16 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white; width: 900px; }
    th.style16 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    table.sheet0 col.col0 { width:92.85555448999999pt }
    table.sheet0 col.col1 { width:97.59999887999999pt }
    table.sheet0 col.col2 { width:97.59999887999999pt }
    table.sheet0 col.col3 { width:83.36666570999999pt }
    table.sheet0 col.col4 { width:83.36666570999999pt }
    table.sheet0 col.col5 { width:26.43333303pt }
    table.sheet0 col.col6 { width:97.59999887999999pt }
    table.sheet0 col.col7 { width:97.59999887999999pt }
    table.sheet0 col.col8 { width:97.59999887999999pt }
    table.sheet0 col.col9 { width:97.59999887999999pt }
    table.sheet0 col.col10 { width:97.59999887999999pt }
    table.sheet0 col.col11 { width:97.59999887999999pt }
    table.sheet0 col.col12 { width:97.59999887999999pt }
    table.sheet0 col.col13 { width:97.59999887999999pt }
    table.sheet0 tr { height:15pt }
    table.sheet0 tr.row0 { height:45pt }
    table.sheet0 tr.row1 { height:47.1pt }
    table.sheet0 tr.row2 { height:45pt }
    table.sheet0 tr.row3 { height:65.09999999999999pt }
    table.sheet0 tr.row4 { height:65.09999999999999pt }
    table.sheet0 tr.row5 { height:44.1pt }
    table.sheet0 tr.row6 { height:30pt }
    table.sheet0 tr.row7 { height:30pt }
    table.sheet0 tr.row8 { height:30pt }
    table.sheet0 tr.row9 { height:60pt }
    table.sheet0 tr.row10 { height:60pt }
    table.sheet0 tr.row11 { height:60pt }
    table.sheet0 tr.row12 { height:60pt }
    table.sheet0 tr.row13 { height:45pt }
    table.sheet0 tr.row14 { height:45pt }
    table.sheet0 tr.row15 { height:45pt }
    table.sheet0 tr.row16 { height:45pt }
    table.sheet0 tr.row17 { height:45pt }
    table.sheet0 tr.row18 { height:45pt }
    table.sheet0 tr.row19 { height:35.1pt }
    table.sheet0 tr.row20 { height:35.1pt }
    table.sheet0 tr.row21 { height:35.1pt }
    table.sheet0 tr.row22 { height:35.1pt }
    table.sheet0 tr.row23 { height:35.1pt }
    table.sheet0 tr.row24 { height:35.1pt }
  </style>
  </head>

  <body>
    
<style>
@page { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
body { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
</style>
<!-- #include file="../../dev/dist/config.asp"-->

<%
  Function GetSQL(ByVal DEC_GameDay, ByVal DEC_GameTitleIDX, ByVal DEC_StadiumIDX, ByVal DEC_StadiumNumber, ByVal DEC_Searchkeyword, ByVal DEC_SearchKey )
    CSQL = " SELECT CCC.GameTitleIDX, dbo.FN_NameSch(CCC.GameTitleIDX, 'GameTitleIDX') AS GameTitleNM, CCC.GameLevelDtlIDX,  CCC.TourneyIDX, CCC.TeamGameNum, CCC.GameNum, CCC.TeamGb, CCC.Level, CCC.LTourneyGroupIDX , CCC.RTourneyGroupIDX,"
    CSQL = CSQL & " 	CCC.TeamGbNM, CCC.LevelNM, CCC.GameTypeNM,"
    CSQL = CSQL & " 	CCC.Result, CCC.ResultType, CCC.ResultNM, CCC.Jumsu,"
    CSQL = CSQL & " 	CCC.GameStatus, CCC.[ROUND], CCC.Sex,"
    CSQL = CSQL & " 	CCC.TempNum, CCC.TurnNum, CCC.GroupGameGb,"
    CSQL = CSQL & " 	CCC.LPlayer1, CCC.LPlayer2, CCC.Rplayer1, CCC.Rplayer2, CCC.LTeam1, CCC.LTeam2, CCC.RTeam1, CCC.RTeam2, CCC.StadiumNum, CCC.StadiumIDX,"
    CSQL = CSQL & " 	CCC.GameDay, CCC.LevelJooNum, CCC.LevelDtlJooNum, CCC.LevelDtlName, dbo.FN_NameSch(CCC.StadiumIDX, 'StadiumIDX') AS StadiumName, PlayLevelType"
    CSQL = CSQL & " FROM "
    CSQL = CSQL & " ("
    CSQL = CSQL & " 	SELECT "
    CSQL = CSQL & " 	BBB.GameTitleIDX, BBB.GameLevelDtlIDX, BBB.TourneyIDX, BBB.TeamGameNum, BBB.GameNum, BBB.TeamGb, BBB.Level, BBB.LTourneyGroupIDX , BBB.RTourneyGroupIDX,"
    CSQL = CSQL & " 	BBB.TeamGbNM, BBB.LevelNM, BBB.GameTypeNM,"
    CSQL = CSQL & " 	BBB.Result, BBB.ResultType, BBB.ResultNM, BBB.Jumsu,"
    CSQL = CSQL & " 	BBB.GameStatus, BBB.[ROUND], BBB.Sex,"
    CSQL = CSQL & " 	ROW_NUMBER() OVER(ORDER BY CONVERT(BIGINT,ISNULL(BBB.TurnNum,'0')), CONVERT(BIGINT,ISNULL(BBB.TeamGameNum,'0')) ASC, CONVERT(BIGINT,ISNULL(BBB.GameNum,'0'))) AS TempNum, TurnNum, PlayLevelType, GroupGameGb, StadiumNum, StadiumIDX,"
    CSQL = CSQL & " 	GameDay, LevelJooNum, LevelDtlJooNum, LevelDtlName,"
    CSQL = CSQL & " 	LPlayer1, LPlayer2, Rplayer1, Rplayer2, LTeam1, LTeam2, RTeam1, RTeam2"
    CSQL = CSQL & " 	FROM"
    CSQL = CSQL & " 	("
    CSQL = CSQL & " 		SELECT AA.GameTitleIDX, AA.GameLevelDtlIDX, AA.TourneyIDX, AA.TeamGameNum, AA.GameNum, AA.TeamGb, AA.Level, AA.LTourneyGroupIDX , AA.RTourneyGroupIDX,"
    CSQL = CSQL & " 		AA.TeamGbNM, AA.LevelNM, AA.GameTypeNM,"
    CSQL = CSQL & " 		AA.Result, AA.ResultType, AA.ResultNM, AA.Jumsu,"
    CSQL = CSQL & " 		AA.GameStatus, AA.[ROUND], AA.Sex, AA.TurnNum, AA.PlayLevelType, AA.GroupGameGb, AA.StadiumNum, AA.StadiumIDX, AA.GameDay, AA.LevelJooNum, AA.LevelDtlJooNum, AA.LevelDtlName,"
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',LPlayers) > 0 THEN LEFT(LPlayers,CHARINDEX('|',LPlayers)-1) ELSE LPlayers END  AS LPlayer1, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',LPlayers) > 0 THEN RIGHT(LPlayers,CHARINDEX('|',REVERSE(LPlayers))-1) ELSE '' END  AS LPlayer2, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',RPlayers) > 0 THEN LEFT(RPlayers,CHARINDEX('|',RPlayers)-1) ELSE RPlayers END AS RPlayer1, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',RPlayers) > 0 THEN RIGHT(RPlayers,CHARINDEX('|',REVERSE(RPlayers))-1) ELSE '' END  AS RPlayer2, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',LTeams) > 0 THEN LEFT(LTeams,CHARINDEX('|',LTeams)-1) ELSE LTeams END AS LTeam1, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',LTeams) > 0 THEN RIGHT(LTeams,CHARINDEX('|',REVERSE(LTeams))-1) ELSE '' END AS LTeam2, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',RTeams) > 0 THEN LEFT(RTeams,CHARINDEX('|',RTeams)-1) ELSE RTeams END AS RTeam1, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',RTeams) > 0 THEN RIGHT(RTeams,CHARINDEX('|',REVERSE(RTeams))-1) ELSE '' END AS RTeam2"
    CSQL = CSQL & " 		FROM"
    CSQL = CSQL & " 		("
    CSQL = CSQL & " 		    SELECT A.GameTitleIDX, A.GameLevelDtlIDX,A.TourneyIDX as TourneyIDX, A.TeamGameNum, A.GameNum, A.TeamGb, A.Level, CONVERT(VARCHAR(10),A.TourneyGroupIDX) AS LTourneyGroupIDX, CONVERT(VARCHAR(10),B.TourneyGroupIDX) AS RTourneyGroupIDX, "
    CSQL = CSQL & " 		    KoreaBadminton.dbo.FN_NameSch(A.TeamGb,'TeamGb') AS TeamGbNM, KoreaBadminton.dbo.FN_NameSch(A.Level,'Level') AS LevelNM,"
    CSQL = CSQL & " 		    KoreaBadminton.dbo.FN_NameSch(D.PlayType,'PubCode') AS GameTypeNM,"
    CSQL = CSQL & " 		    E.Result, dbo.FN_NameSch(E.Result, 'PubType') AS ResultType, dbo.FN_NameSch(E.Result, 'PubCode') AS ResultNM, E.Jumsu,"
    CSQL = CSQL & " 		    KoreaBadminton.dbo.FN_GameStatus(A.GameLevelDtlidx, A.TeamGameNum, A.GameNum) AS GameStatus, A.[ROUND], C.PlayLevelType, A.ORDERBY, dbo.FN_NameSch(D.Sex, 'PubCode') AS Sex,"
    CSQL = CSQL & " 		    A.TurnNum, D.GroupGameGb, A.StadiumNum, A.StadiumIDX, A.GameDay, D.LevelJooNum, C.LevelJooNum AS LevelDtlJooNum, C.LevelDtlName"
    CSQL = CSQL & " 		    ,STUFF(("
    CSQL = CSQL & " 		    		SELECT  DISTINCT (  "
    CSQL = CSQL & " 		    			SELECT  '|'   + UserName "
    CSQL = CSQL & " 		    			FROM    KoreaBadminton.dbo.tblTourneyPlayer  "
    CSQL = CSQL & " 		    			WHERE   TourneyGroupIDX    = AAA.TourneyGroupIDX  "
    CSQL = CSQL & " 						  AND GameLevelDtlidx = AAA.GameLevelDtlidx"
    CSQL = CSQL & " 						  AND DelYN = 'N'"           
    CSQL = CSQL & " 		    			FOR XML PATH('')  "
    CSQL = CSQL & " 		    			)  "
    CSQL = CSQL & " 		    		FROM    KoreaBadminton.dbo.tblTourneyPlayer AAA  "
    CSQL = CSQL & " 		    		WHERE AAA.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    		AND AAA.TourneyGroupIDX = A.TourneyGroupIDX"
    CSQL = CSQL & " 					  AND DelYN = 'N'"         
    CSQL = CSQL & " 		    		),1,1,'') AS LPlayers"
    CSQL = CSQL & " 		    ,STUFF(("
    CSQL = CSQL & " 		    		SELECT  DISTINCT (  "
    CSQL = CSQL & " 		    			SELECT  '|'   + UserName "
    CSQL = CSQL & " 		    			FROM    KoreaBadminton.dbo.tblTourneyPlayer  "
    CSQL = CSQL & " 		    			WHERE   TourneyGroupIDX    = AAA.TourneyGroupIDX  "
    CSQL = CSQL & " 						  AND GameLevelDtlidx = AAA.GameLevelDtlidx"
    CSQL = CSQL & " 						  AND DelYN = 'N'"       
    CSQL = CSQL & " 		    			FOR XML PATH('')  "
    CSQL = CSQL & " 		    			)  "
    CSQL = CSQL & " 		    		FROM    KoreaBadminton.dbo.tblTourneyPlayer AAA  "
    CSQL = CSQL & " 		    		WHERE AAA.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    		AND AAA.TourneyGroupIDX = B.TourneyGroupIDX"
    CSQL = CSQL & " 					  AND DelYN = 'N'"             
    CSQL = CSQL & " 		    		),1,1,'') AS RPlayers"
    CSQL = CSQL & " "
    CSQL = CSQL & " 		    ,STUFF((		"
    CSQL = CSQL & " 		    		SELECT  DISTINCT (  "
    CSQL = CSQL & " 		    			SELECT  '|'   + dbo.FN_NameSch(Team,'Team')"
    CSQL = CSQL & " 		    			FROM    KoreaBadminton.dbo.tblTourneyPlayer  "
    CSQL = CSQL & " 		    			WHERE   TourneyGroupIDX    = AAA.TourneyGroupIDX  "
    CSQL = CSQL & " 						  AND GameLevelDtlidx = AAA.GameLevelDtlidx"
    CSQL = CSQL & " 						  AND DelYN = 'N'"       
    CSQL = CSQL & " 		    			FOR XML PATH('')  "
    CSQL = CSQL & " 		    			)  "
    CSQL = CSQL & " 		    		FROM    KoreaBadminton.dbo.tblTourneyPlayer AAA  "
    CSQL = CSQL & " 		    		WHERE AAA.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    		AND AAA.TourneyGroupIDX = A.TourneyGroupIDX"
    CSQL = CSQL & " 					  AND DelYN = 'N'"             
    CSQL = CSQL & " 		    		),1,1,'') AS LTeams"
    CSQL = CSQL & " 		    ,STUFF((		"
    CSQL = CSQL & " 		    		SELECT  DISTINCT (  "
    CSQL = CSQL & " 		    			SELECT  '|'   + dbo.FN_NameSch(Team,'Team')"
    CSQL = CSQL & " 		    			FROM    KoreaBadminton.dbo.tblTourneyPlayer  "
    CSQL = CSQL & " 		    			WHERE   TourneyGroupIDX    = AAA.TourneyGroupIDX  "
    CSQL = CSQL & " 						  AND GameLevelDtlidx = AAA.GameLevelDtlidx"
    CSQL = CSQL & " 						  AND DelYN = 'N'"       
    CSQL = CSQL & " 		    			FOR XML PATH('')  "
    CSQL = CSQL & " 		    			)  "
    CSQL = CSQL & " 		    		FROM    KoreaBadminton.dbo.tblTourneyPlayer AAA  "
    CSQL = CSQL & " 		    		WHERE AAA.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    		AND AAA.TourneyGroupIDX = B.TourneyGroupIDX"
    CSQL = CSQL & " 					  AND DelYN = 'N'"             
    CSQL = CSQL & " 		    		),1,1,'') AS RTeams"
    CSQL = CSQL & " "
    CSQL = CSQL & " 		    FROM tblTourney A"
    CSQL = CSQL & " 		    INNER JOIN tblTourney B ON B.GameLevelDtlidx = A.GameLevelDtlidx AND B.TeamGameNum = A.TeamGameNum AND B.GameNum = A.GameNum"
    CSQL = CSQL & " 		    INNER JOIN tblGameLevelDtl C ON C.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    INNER JOIN tblGameLevel D ON D.GameLevelidx = C.GameLevelidx"
    CSQL = CSQL & " 		    	LEFT JOIN ("
    CSQL = CSQL & " 		    		SELECT GameLevelDtlidx, TeamGameNum, GameNum, TourneyGroupIDX, Result, Jumsu"
    CSQL = CSQL & " 		    		FROM KoreaBadminton.dbo.tblGameResult"
    CSQL = CSQL & " 		    		WHERE DelYN = 'N'"
    CSQL = CSQL & " 		    		GROUP BY GameLevelDtlidx, TeamGameNum, GameNum, TourneyGroupIDX, Result, Jumsu"
    CSQL = CSQL & " 		    		) AS E ON E.GameLevelDtlidx = A.GameLevelDtlidx AND E.TeamGameNum = A.TeamGameNum AND E.GameNum = A.GameNum AND E.TourneyGroupIDX = A.TourneyGroupIDX    "
    CSQL = CSQL & " 		    WHERE A.DelYN = 'N'"
    CSQL = CSQL & " 		    AND B.DelYN = 'N'"
    CSQL = CSQL & " 		    AND C.DelYN = 'N'"
    CSQL = CSQL & " 		    AND D.DelYN = 'N'"
    CSQL = CSQL & " 		    AND A.ORDERBY < B.ORDERBY"
    CSQL = CSQL & " 		    AND A.GameDay = '" & DEC_GameDay & "'"
    CSQL = CSQL & " 		    AND A.GameTitleIDX = '" & DEC_GameTitleIDX & "'"
    CSQL = CSQL & " 		    AND A.StadiumIDX = '" & DEC_StadiumIDX & "'"

    If DEC_StadiumNumber <> "" Then
      CSQL = CSQL & " 		    AND A.StadiumNum = '" & DEC_StadiumNumber & "'"
    End If
    
    CSQL = CSQL & " 		    AND A.TeamGameNum = '0'"
    CSQL = CSQL & " 		) AS AA"
    CSQL = CSQL & " 		WHERE GameLevelDtlIDX IS NOT NULL"
    CSQL = CSQL & " "
    CSQL = CSQL & " 		UNION ALL"
    CSQL = CSQL & " "
    CSQL = CSQL & " 		SELECT A.GameTitleIDX, A.GameLevelDtlidx, A.TourneyTeamIDX as TourneyIDX, A.TeamGameNum, '0' AS GameNum, A.TeamGb, A.Level, ISNULL(A.Team,'') AS LTourneyGroupIDX, ISNULL(B.Team,'') AS RTourneyGroupIDX,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_NameSch(A.TeamGb,'TeamGb') AS TeamGbNM, KoreaBadminton.dbo.FN_NameSch(A.Level,'Level') AS LevelNM,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_NameSch(D.PlayType,'PubCode') AS GameTypeNM,"
    CSQL = CSQL & " 		E.Result AS Result, dbo.FN_NameSch(E.Result, 'PubType') AS ResultType, dbo.FN_NameSch(E.Result, 'PubCode') AS ResultNM, E.Jumsu,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_GroupGameStatus(A.GameLevelDtlidx, A.TeamGameNum) AS GameStatus, A.[ROUND], dbo.FN_NameSch(D.Sex, 'PubCode') AS Sex,"
    CSQL = CSQL & " 		A.TurnNum, C.PlayLevelType, D.GroupGameGb, A.StadiumNum, A.StadiumIDX, A.GameDay, D.LevelJooNum, C.LevelJooNum AS LevelDtlJooNum, C.LevelDtlName,"
    CSQL = CSQL & " 		'' AS LPlayer1,"
    CSQL = CSQL & " 		'' AS LPlayer2,"
    CSQL = CSQL & " 		'' AS RPlayer1,"
    CSQL = CSQL & " 		'' AS RPlayer2,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_NameSch(A.Team,'Team') AS LTeamNM1, "
    CSQL = CSQL & " 		'' AS LTeamNM2,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_NameSch(B.Team,'Team') AS LTeamNM2,"
    CSQL = CSQL & " 		'' AS LTeamNM2"
    CSQL = CSQL & " 		FROM tblTourneyTeam A"
    CSQL = CSQL & " 		INNER JOIN tblTourneyTeam B ON B.GameLevelDtlidx = A.GameLevelDtlidx AND B.TeamGameNum = A.TeamGameNum"
    CSQL = CSQL & " 		INNER JOIN tblGameLevelDtl C ON C.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		INNER JOIN tblGameLevel D ON D.GameLevelidx = C.GameLevelidx"
    CSQL = CSQL & " 		LEFT JOIN ("
    CSQL = CSQL & " 			SELECT GameLevelDtlidx, TeamGameNum, GameNum, Team, TeamDtl, Result, Jumsu"
    CSQL = CSQL & " 			FROM KoreaBadminton.dbo.tblGroupGameResult"
    CSQL = CSQL & " 			WHERE DelYN = 'N'"
    CSQL = CSQL & " 			) AS E ON E.GameLevelDtlidx = A.GameLevelDtlidx AND E.TeamGameNum = A.TeamGameNum AND E.Team + E.TeamDtl = A.Team + A.TeamDtl"
    CSQL = CSQL & " 		WHERE A.DelYN = 'N'"
    CSQL = CSQL & " 		AND B.DelYN = 'N'"
    CSQL = CSQL & " 		AND A.ORDERBY < B.ORDERBY"
    CSQL = CSQL & " 		AND A.GameDay = '" & DEC_GameDay & "'"
    CSQL = CSQL & " 		AND A.GameTitleIDX = '" & DEC_GameTitleIDX & "'"
    CSQL = CSQL & " 		AND A.StadiumIDX = '" & DEC_StadiumIDX & "'"

    If DEC_StadiumNumber <> "" Then
      CSQL = CSQL & " 		    AND A.StadiumNum = '" & DEC_StadiumNumber & "'"
    End If
    
    CSQL = CSQL & " 		AND A.GameLevelDtlIDX IS NOT NULL"
    CSQL = CSQL & " 	) AS BBB"
    CSQL = CSQL & " ) AS CCC"
    CSQL = CSQL & " WHERE CCC.GameLevelDtlIDX IS NOT NULL"

    If DEC_SearchKey = "UserName" Then
      CSQL = CSQL & " AND (CCC.LPlayer1 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.LPlayer2 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.RPlayer1 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.RPlayer2 LIKE '%" & DEC_Searchkeyword & "%')"
    ElseIf DEC_SearchKey = "Team" Then
      CSQL = CSQL & " AND (CCC.LTeam1 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.LTeam2 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.RTeam1 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.RTeam2 LIKE '%" & DEC_Searchkeyword & "%')"
    End If

    GetSQL = CSQL
  End Function

  Function GetSQLTempNum(ByVal DEC_GameDay, ByVal DEC_GameTitleIDX, ByVal DEC_StadiumIDX, ByVal DEC_StadiumNumber, ByVal DEC_Searchkeyword, ByVal DEC_SearchKey, ByVal Param_TempNum)
    CSQL = " SELECT CCC.GameTitleIDX, dbo.FN_NameSch(CCC.GameTitleIDX, 'GameTitleIDX') AS GameTitleNM, CCC.GameLevelDtlIDX,  CCC.TourneyIDX, CCC.TeamGameNum, CCC.GameNum, CCC.TeamGb, CCC.Level, CCC.LTourneyGroupIDX , CCC.RTourneyGroupIDX,"
    CSQL = CSQL & " 	CCC.TeamGbNM, CCC.LevelNM, CCC.GameTypeNM,"
    CSQL = CSQL & " 	CCC.Result, CCC.ResultType, CCC.ResultNM, CCC.Jumsu,"
    CSQL = CSQL & " 	CCC.GameStatus, CCC.[ROUND], CCC.Sex,"
    CSQL = CSQL & " 	CCC.TempNum, CCC.TurnNum, CCC.GroupGameGb,"
    CSQL = CSQL & " 	CCC.LPlayer1, CCC.LPlayer2, CCC.Rplayer1, CCC.Rplayer2, CCC.LTeam1, CCC.LTeam2, CCC.RTeam1, CCC.RTeam2, CCC.StadiumNum, CCC.StadiumIDX,"
    CSQL = CSQL & " 	CCC.GameDay, CCC.LevelJooNum, CCC.LevelDtlJooNum, CCC.LevelDtlName, dbo.FN_NameSch(CCC.StadiumIDX, 'StadiumIDX') AS StadiumName, PlayLevelType"
    CSQL = CSQL & " FROM "
    CSQL = CSQL & " ("
    CSQL = CSQL & " 	SELECT "
    CSQL = CSQL & " 	BBB.GameTitleIDX, BBB.GameLevelDtlIDX, BBB.TourneyIDX, BBB.TeamGameNum, BBB.GameNum, BBB.TeamGb, BBB.Level, BBB.LTourneyGroupIDX , BBB.RTourneyGroupIDX,"
    CSQL = CSQL & " 	BBB.TeamGbNM, BBB.LevelNM, BBB.GameTypeNM,"
    CSQL = CSQL & " 	BBB.Result, BBB.ResultType, BBB.ResultNM, BBB.Jumsu,"
    CSQL = CSQL & " 	BBB.GameStatus, BBB.[ROUND], BBB.Sex,"
    CSQL = CSQL & " 	ROW_NUMBER() OVER(ORDER BY CONVERT(BIGINT,ISNULL(BBB.TurnNum,'0')), CONVERT(BIGINT,ISNULL(BBB.TeamGameNum,'0')) ASC, CONVERT(BIGINT,ISNULL(BBB.GameNum,'0'))) AS TempNum, TurnNum, PlayLevelType, GroupGameGb, StadiumNum, StadiumIDX,"
    CSQL = CSQL & " 	GameDay, LevelJooNum, LevelDtlJooNum, LevelDtlName,"
    CSQL = CSQL & " 	LPlayer1, LPlayer2, Rplayer1, Rplayer2, LTeam1, LTeam2, RTeam1, RTeam2"
    CSQL = CSQL & " 	FROM"
    CSQL = CSQL & " 	("
    CSQL = CSQL & " 		SELECT AA.GameTitleIDX, AA.GameLevelDtlIDX, AA.TourneyIDX, AA.TeamGameNum, AA.GameNum, AA.TeamGb, AA.Level, AA.LTourneyGroupIDX , AA.RTourneyGroupIDX,"
    CSQL = CSQL & " 		AA.TeamGbNM, AA.LevelNM, AA.GameTypeNM,"
    CSQL = CSQL & " 		AA.Result, AA.ResultType, AA.ResultNM, AA.Jumsu,"
    CSQL = CSQL & " 		AA.GameStatus, AA.[ROUND], AA.Sex, AA.TurnNum, AA.PlayLevelType, AA.GroupGameGb, AA.StadiumNum, AA.StadiumIDX, AA.GameDay, AA.LevelJooNum, AA.LevelDtlJooNum, AA.LevelDtlName,"
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',LPlayers) > 0 THEN LEFT(LPlayers,CHARINDEX('|',LPlayers)-1) ELSE LPlayers END  AS LPlayer1, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',LPlayers) > 0 THEN RIGHT(LPlayers,CHARINDEX('|',REVERSE(LPlayers))-1) ELSE '' END  AS LPlayer2, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',RPlayers) > 0 THEN LEFT(RPlayers,CHARINDEX('|',RPlayers)-1) ELSE RPlayers END AS RPlayer1, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',RPlayers) > 0 THEN RIGHT(RPlayers,CHARINDEX('|',REVERSE(RPlayers))-1) ELSE '' END  AS RPlayer2, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',LTeams) > 0 THEN LEFT(LTeams,CHARINDEX('|',LTeams)-1) ELSE LTeams END AS LTeam1, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',LTeams) > 0 THEN RIGHT(LTeams,CHARINDEX('|',REVERSE(LTeams))-1) ELSE '' END AS LTeam2, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',RTeams) > 0 THEN LEFT(RTeams,CHARINDEX('|',RTeams)-1) ELSE RTeams END AS RTeam1, "
    CSQL = CSQL & " 		CASE WHEN CHARINDEX('|',RTeams) > 0 THEN RIGHT(RTeams,CHARINDEX('|',REVERSE(RTeams))-1) ELSE '' END AS RTeam2"
    CSQL = CSQL & " 		FROM"
    CSQL = CSQL & " 		("
    CSQL = CSQL & " 		    SELECT A.GameTitleIDX, A.GameLevelDtlIDX,A.TourneyIDX as TourneyIDX, A.TeamGameNum, A.GameNum, A.TeamGb, A.Level, CONVERT(VARCHAR(10),A.TourneyGroupIDX) AS LTourneyGroupIDX, CONVERT(VARCHAR(10),B.TourneyGroupIDX) AS RTourneyGroupIDX, "
    CSQL = CSQL & " 		    KoreaBadminton.dbo.FN_NameSch(A.TeamGb,'TeamGb') AS TeamGbNM, KoreaBadminton.dbo.FN_NameSch(A.Level,'Level') AS LevelNM,"
    CSQL = CSQL & " 		    KoreaBadminton.dbo.FN_NameSch(D.PlayType,'PubCode') AS GameTypeNM,"
    CSQL = CSQL & " 		    E.Result, dbo.FN_NameSch(E.Result, 'PubType') AS ResultType, dbo.FN_NameSch(E.Result, 'PubCode') AS ResultNM, E.Jumsu,"
    CSQL = CSQL & " 		    KoreaBadminton.dbo.FN_GameStatus(A.GameLevelDtlidx, A.TeamGameNum, A.GameNum) AS GameStatus, A.[ROUND], C.PlayLevelType, A.ORDERBY, dbo.FN_NameSch(D.Sex, 'PubCode') AS Sex,"
    CSQL = CSQL & " 		    A.TurnNum, D.GroupGameGb, A.StadiumNum, A.StadiumIDX, A.GameDay, D.LevelJooNum, C.LevelJooNum AS LevelDtlJooNum, C.LevelDtlName"
    CSQL = CSQL & " 		    ,STUFF(("
    CSQL = CSQL & " 		    		SELECT  DISTINCT (  "
    CSQL = CSQL & " 		    			SELECT  '|'   + UserName "
    CSQL = CSQL & " 		    			FROM    KoreaBadminton.dbo.tblTourneyPlayer  "
    CSQL = CSQL & " 		    			WHERE   TourneyGroupIDX    = AAA.TourneyGroupIDX  "
    CSQL = CSQL & " 						  AND GameLevelDtlidx = AAA.GameLevelDtlidx"
    CSQL = CSQL & " 						  AND DelYN = 'N'"           
    CSQL = CSQL & " 		    			FOR XML PATH('')  "
    CSQL = CSQL & " 		    			)  "
    CSQL = CSQL & " 		    		FROM    KoreaBadminton.dbo.tblTourneyPlayer AAA  "
    CSQL = CSQL & " 		    		WHERE AAA.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    		AND AAA.TourneyGroupIDX = A.TourneyGroupIDX"
    CSQL = CSQL & " 					  AND DelYN = 'N'"         
    CSQL = CSQL & " 		    		),1,1,'') AS LPlayers"
    CSQL = CSQL & " 		    ,STUFF(("
    CSQL = CSQL & " 		    		SELECT  DISTINCT (  "
    CSQL = CSQL & " 		    			SELECT  '|'   + UserName "
    CSQL = CSQL & " 		    			FROM    KoreaBadminton.dbo.tblTourneyPlayer  "
    CSQL = CSQL & " 		    			WHERE   TourneyGroupIDX    = AAA.TourneyGroupIDX  "
    CSQL = CSQL & " 						  AND GameLevelDtlidx = AAA.GameLevelDtlidx"
    CSQL = CSQL & " 						  AND DelYN = 'N'"       
    CSQL = CSQL & " 		    			FOR XML PATH('')  "
    CSQL = CSQL & " 		    			)  "
    CSQL = CSQL & " 		    		FROM    KoreaBadminton.dbo.tblTourneyPlayer AAA  "
    CSQL = CSQL & " 		    		WHERE AAA.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    		AND AAA.TourneyGroupIDX = B.TourneyGroupIDX"
    CSQL = CSQL & " 					  AND DelYN = 'N'"             
    CSQL = CSQL & " 		    		),1,1,'') AS RPlayers"
    CSQL = CSQL & " "
    CSQL = CSQL & " 		    ,STUFF((		"
    CSQL = CSQL & " 		    		SELECT  DISTINCT (  "
    CSQL = CSQL & " 		    			SELECT  '|'   + dbo.FN_NameSch(Team,'Team')"
    CSQL = CSQL & " 		    			FROM    KoreaBadminton.dbo.tblTourneyPlayer  "
    CSQL = CSQL & " 		    			WHERE   TourneyGroupIDX    = AAA.TourneyGroupIDX  "
    CSQL = CSQL & " 						  AND GameLevelDtlidx = AAA.GameLevelDtlidx"
    CSQL = CSQL & " 						  AND DelYN = 'N'"       
    CSQL = CSQL & " 		    			FOR XML PATH('')  "
    CSQL = CSQL & " 		    			)  "
    CSQL = CSQL & " 		    		FROM    KoreaBadminton.dbo.tblTourneyPlayer AAA  "
    CSQL = CSQL & " 		    		WHERE AAA.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    		AND AAA.TourneyGroupIDX = A.TourneyGroupIDX"
    CSQL = CSQL & " 					  AND DelYN = 'N'"             
    CSQL = CSQL & " 		    		),1,1,'') AS LTeams"
    CSQL = CSQL & " 		    ,STUFF((		"
    CSQL = CSQL & " 		    		SELECT  DISTINCT (  "
    CSQL = CSQL & " 		    			SELECT  '|'   + dbo.FN_NameSch(Team,'Team')"
    CSQL = CSQL & " 		    			FROM    KoreaBadminton.dbo.tblTourneyPlayer  "
    CSQL = CSQL & " 		    			WHERE   TourneyGroupIDX    = AAA.TourneyGroupIDX  "
    CSQL = CSQL & " 						  AND GameLevelDtlidx = AAA.GameLevelDtlidx"
    CSQL = CSQL & " 						  AND DelYN = 'N'"       
    CSQL = CSQL & " 		    			FOR XML PATH('')  "
    CSQL = CSQL & " 		    			)  "
    CSQL = CSQL & " 		    		FROM    KoreaBadminton.dbo.tblTourneyPlayer AAA  "
    CSQL = CSQL & " 		    		WHERE AAA.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    		AND AAA.TourneyGroupIDX = B.TourneyGroupIDX"
    CSQL = CSQL & " 					  AND DelYN = 'N'"             
    CSQL = CSQL & " 		    		),1,1,'') AS RTeams"
    CSQL = CSQL & " "
    CSQL = CSQL & " 		    FROM tblTourney A"
    CSQL = CSQL & " 		    INNER JOIN tblTourney B ON B.GameLevelDtlidx = A.GameLevelDtlidx AND B.TeamGameNum = A.TeamGameNum AND B.GameNum = A.GameNum"
    CSQL = CSQL & " 		    INNER JOIN tblGameLevelDtl C ON C.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		    INNER JOIN tblGameLevel D ON D.GameLevelidx = C.GameLevelidx"
    CSQL = CSQL & " 		    	LEFT JOIN ("
    CSQL = CSQL & " 		    		SELECT GameLevelDtlidx, TeamGameNum, GameNum, TourneyGroupIDX, Result, Jumsu"
    CSQL = CSQL & " 		    		FROM KoreaBadminton.dbo.tblGameResult"
    CSQL = CSQL & " 		    		WHERE DelYN = 'N'"
    CSQL = CSQL & " 		    		GROUP BY GameLevelDtlidx, TeamGameNum, GameNum, TourneyGroupIDX, Result, Jumsu"
    CSQL = CSQL & " 		    		) AS E ON E.GameLevelDtlidx = A.GameLevelDtlidx AND E.TeamGameNum = A.TeamGameNum AND E.GameNum = A.GameNum AND E.TourneyGroupIDX = A.TourneyGroupIDX    "
    CSQL = CSQL & " 		    WHERE A.DelYN = 'N'"
    CSQL = CSQL & " 		    AND B.DelYN = 'N'"
    CSQL = CSQL & " 		    AND C.DelYN = 'N'"
    CSQL = CSQL & " 		    AND D.DelYN = 'N'"
    CSQL = CSQL & " 		    AND A.ORDERBY < B.ORDERBY"
    CSQL = CSQL & " 		    AND A.GameDay = '" & DEC_GameDay & "'"
    CSQL = CSQL & " 		    AND A.GameTitleIDX = '" & DEC_GameTitleIDX & "'"
    CSQL = CSQL & " 		    AND A.StadiumIDX = '" & DEC_StadiumIDX & "'"

    If DEC_StadiumNumber <> "" Then
      CSQL = CSQL & " 		    AND A.StadiumNum = '" & DEC_StadiumNumber & "'"
    End If
    
    CSQL = CSQL & " 		    AND A.TeamGameNum = '0'"
    CSQL = CSQL & " 		) AS AA"
    CSQL = CSQL & " 		WHERE GameLevelDtlIDX IS NOT NULL"
    CSQL = CSQL & " "
    CSQL = CSQL & " 		UNION ALL"
    CSQL = CSQL & " "
    CSQL = CSQL & " 		SELECT A.GameTitleIDX, A.GameLevelDtlidx, A.TourneyTeamIDX as TourneyIDX, A.TeamGameNum, '0' AS GameNum, A.TeamGb, A.Level, ISNULL(A.Team,'') AS LTourneyGroupIDX, ISNULL(B.Team,'') AS RTourneyGroupIDX,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_NameSch(A.TeamGb,'TeamGb') AS TeamGbNM, KoreaBadminton.dbo.FN_NameSch(A.Level,'Level') AS LevelNM,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_NameSch(D.PlayType,'PubCode') AS GameTypeNM,"
    CSQL = CSQL & " 		E.Result AS Result, dbo.FN_NameSch(E.Result, 'PubType') AS ResultType, dbo.FN_NameSch(E.Result, 'PubCode') AS ResultNM, E.Jumsu,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_GroupGameStatus(A.GameLevelDtlidx, A.TeamGameNum) AS GameStatus, A.[ROUND], dbo.FN_NameSch(D.Sex, 'PubCode') AS Sex,"
    CSQL = CSQL & " 		A.TurnNum, C.PlayLevelType, D.GroupGameGb, A.StadiumNum, A.StadiumIDX, A.GameDay, D.LevelJooNum, C.LevelJooNum AS LevelDtlJooNum, C.LevelDtlName,"
    CSQL = CSQL & " 		'' AS LPlayer1,"
    CSQL = CSQL & " 		'' AS LPlayer2,"
    CSQL = CSQL & " 		'' AS RPlayer1,"
    CSQL = CSQL & " 		'' AS RPlayer2,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_NameSch(A.Team,'Team') AS LTeamNM1, "
    CSQL = CSQL & " 		'' AS LTeamNM2,"
    CSQL = CSQL & " 		KoreaBadminton.dbo.FN_NameSch(B.Team,'Team') AS LTeamNM2,"
    CSQL = CSQL & " 		'' AS LTeamNM2"
    CSQL = CSQL & " 		FROM tblTourneyTeam A"
    CSQL = CSQL & " 		INNER JOIN tblTourneyTeam B ON B.GameLevelDtlidx = A.GameLevelDtlidx AND B.TeamGameNum = A.TeamGameNum"
    CSQL = CSQL & " 		INNER JOIN tblGameLevelDtl C ON C.GameLevelDtlidx = A.GameLevelDtlidx"
    CSQL = CSQL & " 		INNER JOIN tblGameLevel D ON D.GameLevelidx = C.GameLevelidx"
    CSQL = CSQL & " 		LEFT JOIN ("
    CSQL = CSQL & " 			SELECT GameLevelDtlidx, TeamGameNum, GameNum, Team, TeamDtl, Result, Jumsu"
    CSQL = CSQL & " 			FROM KoreaBadminton.dbo.tblGroupGameResult"
    CSQL = CSQL & " 			WHERE DelYN = 'N'"
    CSQL = CSQL & " 			) AS E ON E.GameLevelDtlidx = A.GameLevelDtlidx AND E.TeamGameNum = A.TeamGameNum AND E.Team + E.TeamDtl = A.Team + A.TeamDtl"
    CSQL = CSQL & " 		WHERE A.DelYN = 'N'"
    CSQL = CSQL & " 		AND B.DelYN = 'N'"
    CSQL = CSQL & " 		AND A.ORDERBY < B.ORDERBY"
    CSQL = CSQL & " 		AND A.GameDay = '" & DEC_GameDay & "'"
    CSQL = CSQL & " 		AND A.GameTitleIDX = '" & DEC_GameTitleIDX & "'"
    CSQL = CSQL & " 		AND A.StadiumIDX = '" & DEC_StadiumIDX & "'"

    If DEC_StadiumNumber <> "" Then
      CSQL = CSQL & " 		    AND A.StadiumNum = '" & DEC_StadiumNumber & "'"
    End If
    
    CSQL = CSQL & " 		AND A.GameLevelDtlIDX IS NOT NULL"
    CSQL = CSQL & " 	) AS BBB"
    CSQL = CSQL & " ) AS CCC"
    CSQL = CSQL & " WHERE CCC.GameLevelDtlIDX IS NOT NULL"
    CSQL = CSQL & " And (CCC.TempNum = '" & cdbl(Param_TempNum) + 1 & "' OR CCC.TempNum = '" & cdbl(Param_TempNum) + 2 & "')"

    If DEC_SearchKey = "UserName" Then
      CSQL = CSQL & " AND (CCC.LPlayer1 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.LPlayer2 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.RPlayer1 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.RPlayer2 LIKE '%" & DEC_Searchkeyword & "%')"
    ElseIf DEC_SearchKey = "Team" Then
      CSQL = CSQL & " AND (CCC.LTeam1 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.LTeam2 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.RTeam1 LIKE '%" & DEC_Searchkeyword & "%' OR CCC.RTeam2 LIKE '%" & DEC_Searchkeyword & "%')"
    End If

    GetSQLTempNum = CSQL
  End Function
%>

<% 
	Response.CharSet="utf-8"
	Session.codepage="65001"
	Response.codepage="65001"
	Response.ContentType="text/html;charset=utf-8"

	Dim GameTitleIDX	: GameTitleIDX 		= fInject(Request("GameTitleIDX"))
	Dim GameDay		    : GameDay 		    = fInject(Request("GameDay"))	
	Dim StadiumIDX		: StadiumIDX 		= fInject(Request("StadiumIDX"))
  Dim StadiumNum		: StadiumNumber 		= fInject(Request("StadiumNumber"))
	Dim SearchName	: SearchName		= fInject(Request("SearchName"))
  %>
    <a href="./gamePaper_Excel.asp?GameTitleIDX=<%=GameTitleIDX%>&GameDay=<%=GameDay%>&StadiumIDX=<%=StadiumIDX%>&StadiumNumber=<%=StadiumNumber%>&SearchName=<%=SearchName%>">A4 다운하기</a>
    <a href="./gamePaper_Excel_B5.asp?GameTitleIDX=<%=GameTitleIDX%>&GameDay=<%=GameDay%>&StadiumIDX=<%=StadiumIDX%>&StadiumNumber=<%=StadiumNumber%>&SearchName=<%=SearchName%>">B5 다운하기</a>
	<%
    Dim DEC_GameTitleIDX	: DEC_GameTitleIDX 		= crypt.DecryptStringENC(GameTitleIDX)
    Dim DEC_GameDay		    : DEC_GameDay 		    = GameDay
    Dim DEC_StadiumIDX		: DEC_StadiumIDX 		= crypt.DecryptStringENC(StadiumIDX)
    Dim DEC_StadiumNumber	: DEC_StadiumNumber     = StadiumNumber
    Dim DEC_Searchkeyword	: DEC_Searchkeyword		= Searchkeyword
    Dim DEC_GroupGameGb : DEC_GroupGameGb = ""
    'CSQL = GetSQL(DEC_GameDay, DEC_GameTitleIDX, DEC_StadiumIDX,DEC_StadiumNumber, DEC_Searchkeyword,DEC_SearchKey)
    CSQL = " EXEC tblGameTourney_Searched_STR '" & DEC_GameTitleIDX & "', '" & DEC_GameDay & "', '" & DEC_StadiumIDX &"' ,'"  & DEC_StadiumNumber &"','" & "" & "','" & DEC_PlayType & "' ,'" & DEC_TempNum & "'  ,'" & DEC_Searchkey & "'  ,'"  & DEC_Searchkeyword & "','" & DEC_GroupGameGb & "'"
    'Response.Write "CSQL :" & CSQL & "<BR/>"
    const teamGroupGameGb = "B0030002"
    const personGroupGameGb = "B0030001"
    DIM continue : continue = true
    SET CRs = DBCon.Execute(CSQL)

    IF NOT (CRs.Eof Or CRs.Bof) Then
      arrayGamePaper = CRs.getrows()
      arrayGamePaperTempNum = arrayGamePaper
    End If
    'RESPONSE.Write "UBound(arrayGamePaper, 2) " & UBound(arrayGamePaper, 2)  & "<br/>"
    'RESPONSE.Write "UBound(arrayGamePaperTempNum, 2) " & UBound(arrayGamePaperTempNum, 2)  & "<br/>"
    'RESPONSE.END

    CRs.close
   arrayGamePaperCnt = 0
    If IsArray(arrayGamePaper) Then
      For ar = LBound(arrayGamePaper, 2) To UBound(arrayGamePaper, 2) 
        arrayGamePaperCnt = arrayGamePaperCnt + 1
      
        GameTitleIDX = arrayGamePaper(0, ar) 
        GameLevelDtlIDX = arrayGamePaper(1, ar) 
        TeamGameNum = arrayGamePaper(2, ar) 
        GameNum = arrayGamePaper(3, ar) 
        TeamGb = arrayGamePaper(4, ar) 
        Level = arrayGamePaper(5, ar) 
        LTourneyGroupIDX = arrayGamePaper(6, ar) 
        RTourneyGroupIDX = arrayGamePaper(7, ar) 
        TeamGbNM = arrayGamePaper(8, ar) 
        LevelNM = arrayGamePaper(9, ar) 
        PlayTypeNM = arrayGamePaper(10, ar) 
        L_Result = arrayGamePaper(11, ar) 
        L_ResultType = arrayGamePaper(12, ar) 
        L_ResultNM = arrayGamePaper(13, ar) 
        L_Jumsu = arrayGamePaper(14, ar) 
        L_ResultDtl = arrayGamePaper(15, ar) 

        R_Result = arrayGamePaper(16, ar) 
        R_ResultType = arrayGamePaper(17, ar) 
        R_ResultNM = arrayGamePaper(18, ar) 
        R_Jumsu = arrayGamePaper(19, ar) 
        R_ResultDtl = arrayGamePaper(20, ar) 
        GameStatus = arrayGamePaper(21, ar) 
        ROUNDS = arrayGamePaper(22, ar) 
        Sex = arrayGamePaper(23, ar) 
        TempNum = arrayGamePaper(24, ar) 
        TurnNum = arrayGamePaper(25, ar) 
        GroupGameGb = arrayGamePaper(26, ar) 
        TourneyCnt = arrayGamePaper(27, ar) 
        LTeamDtl = arrayGamePaper(28, ar) 
        RTeamDtl = arrayGamePaper(29, ar) 
        LPlayer1 = arrayGamePaper(30, ar) 
        LPlayer2 = arrayGamePaper(31, ar) 
        Rplayer1 = arrayGamePaper(32, ar) 
        Rplayer2 = arrayGamePaper(33, ar) 

        LTeam1 = arrayGamePaper(34, ar) 
        LTeam2 = arrayGamePaper(35, ar) 
        RTeam1 = arrayGamePaper(36, ar) 
        RTeam2 = arrayGamePaper(37, ar) 

        StadiumNum = arrayGamePaper(38, ar) 
        StadiumIDX = arrayGamePaper(39, ar) 
        GameDay = arrayGamePaper(40, ar) 
        LevelJooNum = arrayGamePaper(41, ar) 
        LevelDtlJooNum = arrayGamePaper(42, ar) 
        LevelDtlName = arrayGamePaper(43, ar) 
        StadiumName = arrayGamePaper(44, ar) 
        PlayLevelType = arrayGamePaper(45, ar) 
        LevelJooName = arrayGamePaper(46, ar) 

        MaxRound = arrayGamePaper(47, ar) 
        GameType = arrayGamePaper(48, ar) 
        GameTypeNM = arrayGamePaper(49, ar)
        ResultGangSu = GetGangSu(GameType, MaxRound,ROUNDS) 
   
%>
  
  <table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0">
    <col class="col0">
    <col class="col1">
    <col class="col2">
    <col class="col3">
    <col class="col4">
    <col class="col5">
    <col class="col6">
    <col class="col7">
    <col class="col8">
    <col class="col9">
    <col class="col10">
    <col class="col11">
    <col class="col12">
    <col class="col13">
    <tbody>
      <tr class="row0">
      <td class="column0 style0 null">
      <div style="position: relative;"><img style="position: absolute; z-index: 1; left: 3px; top: -18px; width: 143px; height: 47px;" src="./logo/badminton.png" border="0" /></div></td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4 style0 null">
      <div style="position: relative;"><img style="position: absolute; z-index: 1; left: 8px; top: -18px; width: 132px; height: 42px;" src="./logo/sd.png" border="0" /></div></td>
      <td class="column5 style7 null"></td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row1">
      <td class="column0 style9 s">No. <span style="font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:26pt"><%=TempNum%></span></td>
      <td class="column1 style10 s">
      <span style="color:#000000; font-family:'맑은 고딕'; font-size:13pt">
        <%=Sex & PlayTypeNM & " " & TeamGbNM & " " & LevelNM & LevelJooNum & " "%>
        </span>
      </td>
      <td class="column2 style10 s">
      
      <%
        If PlayLevelType = "B0100001" Then
          Response.Write "예선 " & LevelDtlJooNum & "조"
        ElseIf PlayLevelType = "B0100002" Then
          IF ResultGangSu = "" Then
            Response.Write " 본선" 
          Else
            Response.Write " 본선" & "-" & ResultGangSu
          ENd IF
        Else
          Response.Write "-"
        End If  
      %>      
      </td>
      <td class="column3 style10 s"><span style="font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:26pt"><%=StadiumNum%></span><span style="color:#000000; font-family:'맑은 고딕'; font-size:18pt"> 코트</span></td>
      <td class="column4 style10 s"><span style="font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:26pt">
        <%
        IF GroupGameGb = teamGroupGameGb Then
            Response.Write TeamGameNum
        ELSE
            Response.Write GameNum
        End IF
        %>
        </span><span style="color:#000000; font-family:'맑은 고딕'; font-size:18pt"> 경기</span>
      </td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row2">
      <% if GroupGameGb = personGroupGameGb Then %>
      <td class="column0 style2 s">소 속</td>
      <% END IF%>

      <% if GroupGameGb = personGroupGameGb Then %>
      <td class="column1 style14 s style14" colspan="3">이 름</td>
      <%ELSE%>
      <td class="column1 style14 s style14" colspan="3">팀 명</td>
      <% END IF%>
      <td class="column3 style3 s">점 수</td>
      <td class="column4 style3 s">서 명</td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row3">
      
      <% if GroupGameGb = personGroupGameGb Then %>
      <td class="column0 style4 s"><%=LTeam1%></td>
      <td class="column1 style12 s style12" colspan="3"><%=LPlayer1%> / <%=LPlayer2%></td>
      <%ELSE%>
      <td class="column0 style4 s"  colspan="3"><%=LTeam1%></td>
      <% END IF%>
      <td class="column3 style4 null"></td>
      <td class="column4 style4 null"></td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row4">
       <% if GroupGameGb = personGroupGameGb Then %>
      <td class="column0 style5 s"><%=RTeam1%></td>
      <td class="column1 style13 s style13" colspan="3"><%=RPlayer1%> / <%=RPlayer2%></td>
      <%ELSE%>
      <td class="column0 style5 s" colspan="3"><%=RTeam1%></td>
      <% END IF%>
      <td class="column3 style5 null"></td>
      <td class="column4 style5 null"></td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row5">
      <td class="column0 style1 null"></td>
      <td class="column1 style15 n style15" colspan="2"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row6">
      <%
        'arrayGamePaperTempNum =null 
        'CSQLTempNum = GetSQLTempNum(DEC_GameDay, DEC_GameTitleIDX, DEC_StadiumIDX,DEC_StadiumNumber, DEC_Searchkeyword,DEC_SearchKey,TempNum)
        'CSQLTempNum = " EXEC tblGameTourney_Searched_STR '" & DEC_GameTitleIDX & "', '" & DEC_GameDay & "', '" & DEC_StadiumIDX &"' ,'"  & DEC_StadiumNumber &"','" & "" & "','" & DEC_PlayType & "' ,'" & TempNum & "'  ,'" & DEC_Searchkey & "'  ,'"  & DEC_Searchkeyword & "','" & DEC_GroupGameGb & "'"
        'Response.Write "CSQLTempNum" & CSQLTempNum& "<br>"
        'Response.End
        'Response.Write "CSQLTempNum" & CSQLTempNum& "<br>"
        'SET CRsTempNum = DBCon.Execute(CSQLTempNum)
        
        'IF NOT (CRsTempNum.Eof and CRsTempNum.Bof) Then
        '  arrayGamePaperTempNum = CRsTempNum.getrows()
        'End If
        'CRsTempNum.close

        'Response.Write "IsArray(arrayGamePaperTempNum)" & IsArray(arrayGamePaperTempNum) & "<br>"

        arrayTempNumCnt = 0
       
        If IsArray(arrayGamePaperTempNum) Then
          For ar_TempNum = LBound(arrayGamePaperTempNum, 2) To UBound(arrayGamePaperTempNum, 2) 
           
            continue = false
            'Response.Write "arrayTempNumCnt" & arrayTempNumCnt & "<br>"
            B_GameTitleIDX = arrayGamePaperTempNum(0, ar_TempNum) 
            B_GameLevelDtlIDX = arrayGamePaperTempNum(1, ar_TempNum) 
            B_TeamGameNum = arrayGamePaperTempNum(2, ar_TempNum) 
            B_GameNum = arrayGamePaperTempNum(3, ar_TempNum) 
            B_TeamGb = arrayGamePaperTempNum(4, ar_TempNum) 
            B_Level = arrayGamePaperTempNum(5, ar_TempNum) 
            B_LTourneyGroupIDX = arrayGamePaperTempNum(6, ar_TempNum) 
            B_RTourneyGroupIDX = arrayGamePaperTempNum(7, ar_TempNum) 
            B_TeamGbNM = arrayGamePaperTempNum(8, ar_TempNum) 
            B_LevelNM = arrayGamePaperTempNum(9, ar_TempNum) 
            B_PlayTypeNM = arrayGamePaperTempNum(10, ar_TempNum) 
            B_LResult = arrayGamePaperTempNum(11, ar_TempNum) 
            B_LResultType = arrayGamePaperTempNum(12,ar_TempNum) 
            B_LResultNM = arrayGamePaperTempNum(13, ar_TempNum) 
            B_LJumsu = arrayGamePaperTempNum(14, ar_TempNum) 
            B_LResultDtl = arrayGamePaperTempNum(15, ar_TempNum) 

            B_RResult = arrayGamePaperTempNum(16, ar_TempNum) 
            B_RResultType = arrayGamePaperTempNum(17, ar_TempNum) 
            B_RResultNM = arrayGamePaperTempNum(18, ar_TempNum) 
            B_RJumsu = arrayGamePaperTempNum(19, ar_TempNum) 
            B_RResultDtl = arrayGamePaperTempNum(20, ar_TempNum) 
            B_GameStatus = arrayGamePaperTempNum(21, ar_TempNum) 
            B_ROUNDS = arrayGamePaperTempNum(22, ar_TempNum) 
            B_Sex = arrayGamePaperTempNum(23, ar_TempNum) 
            B_TempNum = arrayGamePaperTempNum(24, ar_TempNum) 
            B_TurnNum = arrayGamePaperTempNum(25, ar_TempNum) 
            B_GroupGameGb = arrayGamePaperTempNum(26, ar_TempNum) 
            B_TourneyCnt = arrayGamePaperTempNum(27, ar_TempNum) 
            B_LTeamDtl = arrayGamePaperTempNum(28, ar_TempNum) 
            B_RTeamDtl = arrayGamePaperTempNum(29, ar_TempNum) 
            B_LPlayer1 = arrayGamePaperTempNum(30, ar_TempNum) 
            B_LPlayer2 = arrayGamePaperTempNum(31, ar_TempNum) 
            B_Rplayer1 = arrayGamePaperTempNum(32, ar_TempNum) 
            B_Rplayer2 = arrayGamePaperTempNum(33, ar_TempNum) 

            B_LTeam1 = arrayGamePaperTempNum(34, ar_TempNum) 
            B_LTeam2 = arrayGamePaperTempNum(35, ar_TempNum) 
            B_RTeam1 = arrayGamePaperTempNum(36, ar_TempNum) 
            B_RTeam2 = arrayGamePaperTempNum(37, ar_TempNum) 

            B_StadiumNum = arrayGamePaperTempNum(38, ar_TempNum) 
            B_StadiumIDX = arrayGamePaperTempNum(39, ar_TempNum) 
            B_GameDay = arrayGamePaperTempNum(40, ar_TempNum) 
            B_LevelJooNum = arrayGamePaperTempNum(41, ar_TempNum) 
            B_LevelDtlJooNum = arrayGamePaperTempNum(42, ar_TempNum) 
            B_LevelDtlName = arrayGamePaperTempNum(43, ar_TempNum) 
            B_StadiumName = arrayGamePaperTempNum(44, ar_TempNum) 
            B_PlayLevelType = arrayGamePaperTempNum(45, ar_TempNum) 
            B_LevelJooName = arrayGamePaperTempNum(46, ar_TempNum) 

            B_MaxRound = arrayGamePaperTempNum(47, ar_TempNum) 
            B_GameType = arrayGamePaperTempNum(48, ar_TempNum) 
            B_GameTypeNM = arrayGamePaperTempNum(49, ar_TempNum) 
            B_ResultGangSu = GetGangSu(B_GameType, B_MaxRound,B_ROUNDS)

            TempNum1 = cdbl(TempNum) + 1
            TempNum2 = cdbl(TempNum1) + 1

            If CDBL(B_TempNum) < CDBL(TempNum1) Then 
              continue = false
            Else  
              arrayTempNumCnt = arrayTempNumCnt + 1
              continue = true
            End IF

            IF CDBL(TempNum2) < CDBL(B_TempNum) Then  
                'Response.Write "Exit For : "  & "<br/>"
              Exit For
            END IF

            'Response.Write "continue :" & continue & "<br/>"
            
            IF (continue = true) Then
              'Response.Write "TempNum :" & TempNum & "<br/>"
              'Response.Write "B_TempNum: " & B_TempNum & "<br/>"
              'Response.Write "TempNum1 : " & TempNum1 & "<br/>"
              'Response.Write "TempNum2 : " & TempNum2 & "<br/>"
              
              if cdbl(arrayTempNumCnt) = 1 Then
                if B_GroupGameGb = teamGroupGameGb Then 
                  Response.Write "<td class='column0 style16 s style11' colspan='5'>다음경기 "
                  If B_PlayLevelType = "B0100001" Then
                    Response.Write "예선 " & B_LevelDtlJooNum & "조"
                  ElseIf B_PlayLevelType = "B0100002" Then
                    IF B_ResultGangSu = "" Then
                      Response.Write " 본선" 
                    Else
                      Response.Write " 본선" & "-" & B_ResultGangSu
                    ENd IF
                  Else
                    Response.Write "-"
                  End If  
                  Response.Write "(" & B_LTeam1 & " / " & B_RTeam1 & ")  ▷ " & B_StadiumNum & "코트 " & B_TeamGameNum & " 경기 예정</td>"
                else
                  Response.Write "<td class='column0 style16 s style11' colspan='5'>다음경기 "
                  If B_PlayLevelType = "B0100001" Then
                    Response.Write "예선 " & B_LevelDtlJooNum & "조"
                  ElseIf B_PlayLevelType = "B0100002" Then
                    IF B_ResultGangSu = "" Then
                      Response.Write " 본선" 
                    Else
                      Response.Write " 본선" & "-" & B_ResultGangSu
                    ENd iF
                  Else
                    Response.Write "-"
                  End If  
                  Response.Write  "(" & B_LPlayer1 & "," & B_LPlayer2  & " / (" & B_RPlayer1 & ", " & B_RPlayer2 & ")  ▷ " & B_StadiumNum & "코트 " & B_GameNum & " 경기 예정</td>"
                End IF

              Response.Write "<td class='column5 style7 null'></td>"
              Response.Write "<td class='column6 style1 null'></td>"
              Response.Write "<td class='column7 style1 null'></td>"
              Response.Write "<td class='column8 style1 null'></td>"
              Response.Write "<td class='column9 style1 null'></td>"
              Response.Write "<td class='column10'>&nbsp;</td>"
              Response.Write "<td class='column11'>&nbsp;</td>"
              Response.Write "<td class='column12'>&nbsp;</td>"
              Response.Write "<td class='column13'>&nbsp;</td>"
              Response.Write "</tr>"
              Response.Write "<tr class='row7'>"
              Response.Write "<tr class='row7'>"
              End IF

            
              if cdbl(arrayTempNumCnt) = 2 Then
                if B_GroupGameGb = teamGroupGameGb Then 
                  Response.Write "<td class='column0 style16 s style11' colspan='5'>다음경기 "
                  If B_PlayLevelType = "B0100001" Then
                    Response.Write "예선 " & B_LevelDtlJooNum & "조"
                  ElseIf B_PlayLevelType = "B0100002" Then
                      IF B_ResultGangSu = "" Then
                      Response.Write " 본선" 
                    Else
                      Response.Write " 본선" & "-" & B_ResultGangSu
                    ENd iF
                  Else
                    Response.Write "-"
                  End If  
                  Response.Write "(" & B_LTeam1 & " / " & B_RTeam1 & ")  ▷ " & B_StadiumNum & "코트 " & B_TeamGameNum & " 경기 예정</td>"
                else
                  Response.Write "<td class='column0 style16 s style11' colspan='5'>다음경기 "
                  If B_PlayLevelType = "B0100001" Then
                    Response.Write "예선 " & B_LevelDtlJooNum & "조"
                  ElseIf B_PlayLevelType = "B0100002" Then
                      IF B_ResultGangSu = "" Then
                      Response.Write " 본선" 
                    Else
                      Response.Write " 본선" & "-" & B_ResultGangSu
                    ENd iF
                  Else
                    Response.Write "-"
                  End If  
                  Response.Write  "(" & B_LPlayer1 & "," & B_LPlayer2  & " / (" & B_RPlayer1 & ", " & B_RPlayer2 & ")  ▷ " & B_StadiumNum & "코트 " & B_GameNum & " 경기 예정</td>"
                End IF
              End IF
            END IF
          NEXT
        END IF
      %>

      <!--<td class="column0 style16 s style11" colspan="5">다음경기 (이은수 / 이미경) -&gt; 12:30 ▷ 17코트 3경기 예정 (53)</td>-->
      <!--<td class="column0 style11 s style11" colspan="5">다음경기 (이동욱 / 김연옥) -&gt; 12:30 ▷ 16코트 3경기 예정 (52)</td>-->
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row8">
      <td class="column0 style6 null"></td>
      <td class="column1 style6 null"></td>
      <td class="column2 style6 null"></td>
      <td class="column3 style6 null"></td>
      <td class="column4 style6 null"></td>
      <td class="column5 style8 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row9">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row10">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row11">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row12">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row13">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row14">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row15">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row16">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row17">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row18">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row19">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row20">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row21">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row22">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row23">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row24">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
    </tbody>
  </table>
<%
    NEXT
  End If          
%>  
  </body>
</html>

<%
  DBClose()
%>
