<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="author" content="Windows 사용자" />
    <meta name="company" content="Microsoft Corporation" />
    <title>배드민턴 경기기록지</title>
  <style type="text/css">
    html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
    table { border-collapse:collapse; page-break-after:always }
    .gridlines td { border:1px dotted black }
    .gridlines th { border:1px dotted black }
    .b { text-align:center }
    .e { text-align:center }
    .f { text-align:right }
    .inlineStr { text-align:left }
    .n { text-align:right }
    .s { text-align:left }
    td.style0 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style0 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style1 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style1 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style2 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    th.style2 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    td.style3 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    th.style3 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    td.style4 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:20pt; background-color:white }
    th.style4 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:20pt; background-color:white }
    td.style5 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:20pt; background-color:white }
    th.style5 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:20pt; background-color:white }
    td.style6 { vertical-align:middle; text-align:center; /*border-bottom:2px solid #000000 !important;*/ border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style6 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style7 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; /*border-right:2px solid #000000 !important;*/ color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style7 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; /*border-right:2px solid #000000 !important;*/ color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style8 { vertical-align:middle; text-align:center; /*border-bottom:2px solid #000000 !important;*/ border-top:none #000000; border-left:none #000000; /*border-right:2px solid #000000 !important;*/ color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    th.style8 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; /*border-right:2px solid #000000 !important;*/ color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
    td.style9 { vertical-align:bottom; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    th.style9 { vertical-align:bottom; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    td.style10 { vertical-align:bottom; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    th.style10 { vertical-align:bottom; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    td.style11 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    th.style11 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    td.style12 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:24pt; background-color:white }
    th.style12 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:24pt; background-color:white }
    td.style13 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:24pt; background-color:white }
    th.style13 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:24pt; background-color:white }
    td.style14 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    th.style14 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'맑은 고딕'; font-size:16pt; background-color:white }
    td.style15 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:28pt; background-color:white }
    th.style15 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:28pt; background-color:white }
    td.style16 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white; width: 900px; }
    th.style16 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:18pt; background-color:white }
    table.sheet0 col.col0 { width:92.85555448999999pt }
    table.sheet0 col.col1 { width:97.59999887999999pt }
    table.sheet0 col.col2 { width:97.59999887999999pt }
    table.sheet0 col.col3 { width:83.36666570999999pt }
    table.sheet0 col.col4 { width:83.36666570999999pt }
    table.sheet0 col.col5 { width:26.43333303pt }
    table.sheet0 col.col6 { width:97.59999887999999pt }
    table.sheet0 col.col7 { width:97.59999887999999pt }
    table.sheet0 col.col8 { width:97.59999887999999pt }
    table.sheet0 col.col9 { width:97.59999887999999pt }
    table.sheet0 col.col10 { width:97.59999887999999pt }
    table.sheet0 col.col11 { width:97.59999887999999pt }
    table.sheet0 col.col12 { width:97.59999887999999pt }
    table.sheet0 col.col13 { width:97.59999887999999pt }
    table.sheet0 tr { height:15pt }
    table.sheet0 tr.row0 { height:45pt }
    table.sheet0 tr.row1 { height:47.1pt }
    table.sheet0 tr.row2 { height:45pt }
    table.sheet0 tr.row3 { height:65.09999999999999pt }
    table.sheet0 tr.row4 { height:65.09999999999999pt }
    table.sheet0 tr.row5 { height:44.1pt }
    table.sheet0 tr.row6 { height:30pt }
    table.sheet0 tr.row7 { height:30pt }
    table.sheet0 tr.row8 { height:30pt }
    table.sheet0 tr.row9 { height:60pt }
    table.sheet0 tr.row10 { height:60pt }
    table.sheet0 tr.row11 { height:60pt }
    table.sheet0 tr.row12 { height:60pt }
    table.sheet0 tr.row13 { height:45pt }
    table.sheet0 tr.row14 { height:45pt }
    table.sheet0 tr.row15 { height:45pt }
    table.sheet0 tr.row16 { height:45pt }
    table.sheet0 tr.row17 { height:45pt }
    table.sheet0 tr.row18 { height:45pt }
    table.sheet0 tr.row19 { height:35.1pt }
    table.sheet0 tr.row20 { height:35.1pt }
    table.sheet0 tr.row21 { height:35.1pt }
    table.sheet0 tr.row22 { height:35.1pt }
    table.sheet0 tr.row23 { height:35.1pt }
    table.sheet0 tr.row24 { height:35.1pt }
  </style>
  </head>

  <body>
    
<style>
@page { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
body { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
</style>
<!-- #include file="../../dev/dist/config.asp"-->
<!-- #include file="../../classes/JSON_2.0.4.asp" -->
<!-- #include file="../../classes/JSON_UTIL_0.1.1.asp" -->
<!-- #include file="../../classes/json2.asp" -->
<script language="Javascript" runat="server">
function hasown(obj,  prop){
	if (obj.hasOwnProperty(prop) == true){
		return "ok";
	}
	else{
		return "notok";
	}
}
</script>

<% 
	Response.CharSet="utf-8"
	Session.codepage="65001"
	Response.codepage="65001"
	Response.ContentType="text/html;charset=utf-8"

  'REQ = "{""CMD"":19,""tGameLevelDtlIDX"":""666A8713D43C6EF5BCB3D19DE7D38F1E"",""tTeamGameNum"":""1""}"
  'Set oJSONoutput = JSON.Parse(REQ)

  Dim GameLevelDtlIDX	: GameLevelDtlIDX 		= fInject(Request("GameLevelDtlIDX"))
	Dim TeamGameNum		    : TeamGameNum 		    = fInject(Request("TeamGameNum"))	
  Dim DEC_GameLevelDtlIDX	: DEC_GameLevelDtlIDX 		= crypt.DecryptStringENC(GameLevelDtlIDX)
  Dim DEC_TeamGameNum		    : DEC_TeamGameNum		    = TeamGameNum

  'If hasown(oJSONoutput, "tGameLevelDtlIDX") = "ok" then
  '  If ISNull(oJSONoutput.tGameLevelDtlIDX) Or oJSONoutput.tGameLevelDtlIDX = "" Then
  '    GameLevelDtlIDX = ""
  '    DEC_GameLevelDtlIDX = ""
  '  Else
  '    GameLevelDtlIDX = fInject(oJSONoutput.tGameLevelDtlIDX)
  '    DEC_GameLevelDtlIDX = fInject(crypt.DecryptStringENC(oJSONoutput.tGameLevelDtlIDX))    
  '  End If
  'End if  
  'If hasown(oJSONoutput, "tTeamGameNum") = "ok" then
  '  If ISNull(oJSONoutput.tTeamGameNum) Or oJSONoutput.tTeamGameNum = "" Then
  '    TeamGameNum = ""
  '    DEC_TeamGameNum = ""
  '  Else
  '    TeamGameNum = fInject(oJSONoutput.tTeamGameNum)
  '    DEC_TeamGameNum = fInject(crypt.DecryptStringENC(oJSONoutput.tTeamGameNum))    
  '  End If
  'End if  

  'Response.Write "DEC_GameLevelDtlIDX : " & DEC_GameLevelDtlIDX & "<br/>"
  'Response.Write "TeamGameNum : " & TeamGameNum & "<br/>"
  
  %>
    <a href="./gameOrderPaper_Excel.asp?GameLevelDtlIDX=<%=GameLevelDtlIDX%>&TeamGameNum=<%=TeamGameNum%>">A4 다운하기</a>
    <a href="./gameOrderPaper_Excel_B5.asp?GameLevelDtlIDX=<%=GameLevelDtlIDX%>&TeamGameNum=<%=TeamGameNum%>">B5 다운하기</a>
	<%
    'CSQL = GetSQL(DEC_GameDay, DEC_GameTitleIDX, DEC_StadiumIDX,DEC_StadiumNumber, DEC_Searchkeyword,DEC_SearchKey)
    TempNum = ""
    CSQL = " EXEC tblGameTeamTourneyOrder_Searched_STR '" & DEC_GameLevelDtlIDX & "', '" & TeamGameNum & "', '" & TempNum & "'"

    'Response.Write "CSQL :" & CSQL & "<BR/>"
    
    const teamGroupGameGb = "B0030002"
    const personGroupGameGb = "B0030001"

    SET CRs = DBCon.Execute(CSQL)

    IF NOT (CRs.Eof Or CRs.Bof) Then
      arrayGamePaper = CRs.getrows()
    End If
    CRs.close
   
    If IsArray(arrayGamePaper) Then
      For ar = LBound(arrayGamePaper, 2) To UBound(arrayGamePaper, 2) 
        GameTitleIDX = arrayGamePaper(0, ar) 
        GameLevelDtlIDX = arrayGamePaper(1, ar) 
        TeamGameNum = arrayGamePaper(2, ar) 
        GameNum = arrayGamePaper(3, ar) 
        TeamGb = arrayGamePaper(4, ar) 
        Level = arrayGamePaper(5, ar) 
        LTourneyGroupIDX = arrayGamePaper(6, ar) 
        RTourneyGroupIDX = arrayGamePaper(7, ar) 
        TeamGbNM = arrayGamePaper(8, ar) 
        LevelNM = arrayGamePaper(9, ar) 
        PlayTypeNM = arrayGamePaper(10, ar) 
        L_Result = arrayGamePaper(11, ar) 
        L_ResultType = arrayGamePaper(12, ar) 
        L_ResultNM = arrayGamePaper(13, ar) 
        L_Jumsu = arrayGamePaper(14, ar) 
        L_ResultDtl = arrayGamePaper(15, ar) 
        R_Result = arrayGamePaper(16, ar) 
        R_ResultType = arrayGamePaper(17, ar) 
        R_ResultNM = arrayGamePaper(18, ar) 
        R_Jumsu = arrayGamePaper(19, ar) 
        R_ResultDtl = arrayGamePaper(20, ar) 
        GameStatus = arrayGamePaper(21, ar) 
        ROUNDS = arrayGamePaper(22, ar) 
        Sex = arrayGamePaper(23, ar) 
        TempNum = arrayGamePaper(24, ar) 
        TurnNum = arrayGamePaper(25, ar) 
        GroupGameGb = arrayGamePaper(26, ar) 
        TourneyCnt = arrayGamePaper(27, ar) 

        'LTeamDtl = arrayGamePaper(28, ar) 
        'RTeamDtl = arrayGamePaper(29, ar) 
        LPlayer1 = arrayGamePaper(28, ar) 
        LPlayer2 = arrayGamePaper(29, ar) 
        Rplayer1 = arrayGamePaper(30, ar) 
        Rplayer2 = arrayGamePaper(31, ar) 

        LTeam1 = arrayGamePaper(32, ar) 
        LTeam2 = arrayGamePaper(33, ar) 
        RTeam1 = arrayGamePaper(34, ar) 
        RTeam2 = arrayGamePaper(35, ar) 

        StadiumNum = arrayGamePaper(36, ar) 
        StadiumIDX = arrayGamePaper(37, ar) 
        GameDay = arrayGamePaper(38, ar) 

        LevelJooNum = arrayGamePaper(39, ar) 
        LevelDtlJooNum = arrayGamePaper(40, ar) 
        LevelDtlName = arrayGamePaper(41, ar) 
        StadiumName = arrayGamePaper(42, ar) 

        PlayLevelType = arrayGamePaper(43, ar) 
        LevelJooName = arrayGamePaper(44, ar) 

        Win_TourneyGroupIDX = arrayGamePaper(45, ar) 
        LGroupJumsu = arrayGamePaper(46, ar) 
        RGroupJumsu = arrayGamePaper(47, ar) 
        LDtlJumsu = arrayGamePaper(48, ar) 
        RDtlJumsu = arrayGamePaper(49, ar) 
        SignData = arrayGamePaper(50, ar) 

        MaxRound = arrayGamePaper(51, ar) 
        GameType = arrayGamePaper(52, ar) 
        GameTypeNM = arrayGamePaper(53, ar)
        ResultGangSu = GetGangSu(GameType, MaxRound,ROUNDS) 
   
%>
  
  <table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0">
    <col class="col0">
    <col class="col1">
    <col class="col2">
    <col class="col3">
    <col class="col4">
    <col class="col5">
    <col class="col6">
    <col class="col7">
    <col class="col8">
    <col class="col9">
    <col class="col10">
    <col class="col11">
    <col class="col12">
    <col class="col13">
    <tbody>
      <tr class="row0">
      <td class="column0 style0 null">
      <div style="position: relative;"><img style="position: absolute; z-index: 1; left: 3px; top: -18px; width: 143px; height: 47px;" src="./logo/badminton.png" border="0" /></div></td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4 style0 null">
      <div style="position: relative;"><img style="position: absolute; z-index: 1; left: 8px; top: -18px; width: 132px; height: 42px;" src="./logo/sd.png" border="0" /></div></td>
      <td class="column5 style7 null"></td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row1">
      <td class="column0 style9 s">No. <span style="font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:26pt"><%=TempNum%></span></td>
      <td class="column1 style10 s">
      <span style="color:#000000; font-family:'맑은 고딕'; font-size:13pt">
        <%= Sex & PlayTypeNM & " " & TeamGbNM & " " & LevelNM & LevelJooNum & " "%>
        </span>
      </td>
      <td class="column2 style10 s">
      
      <%
        If PlayLevelType = "B0100001" Then
          Response.Write "예선 " & LevelDtlJooNum & "조"
        ElseIf PlayLevelType = "B0100002" Then
          IF ResultGangSu = "" Then
            Response.Write " 본선" 
          Else
            Response.Write " 본선" & "-" & ResultGangSu
          ENd IF
        Else
          Response.Write "-"
        End If  
      %>      
      </td>
      <td class="column3 style10 s"><span style="font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:23pt"><%=StadiumNum%></span><span style="color:#000000; font-family:'맑은 고딕'; font-size:18pt"> 코트</span></td>
      <td class="column4 style10 s"><span style="font-weight:bold; color:#000000; font-family:'맑은 고딕'; font-size:23pt">
      <%
          Response.Write TeamGameNum & "-" & GameNum
      %>
        </span><span style="color:#000000; font-family:'맑은 고딕'; font-size:18pt">경기</span>
      </td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row2">
      <td class="column0 style2 s">소 속</td>
      <td class="column1 style14 s style14" colspan="3">이 름</td>
      <td class="column3 style3 s">점 수</td>
      <td class="column4 style3 s">서 명</td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row3">
      
      <td class="column0 style4 s"><%=LTeam1%></td>
      <td class="column1 style12 s style12" colspan="3"><%=LPlayer1%> / <%=LPlayer2%></td>
      
      <td class="column3 style4 null"></td>
      <td class="column4 style4 null"></td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row4">
       
      <td class="column0 style5 s"><%=RTeam1%></td>
      <td class="column1 style13 s style13" colspan="3"><%=RPlayer1%> / <%=RPlayer2%></td>
      <td class="column3 style5 null"></td>
      <td class="column4 style5 null"></td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row5">
      <td class="column0 style1 null"></td>
      <td class="column1 style15 n style15" colspan="2"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row6">
      <%
        arrayGamePaperTempNum =null 
        'CSQLTempNum = GetSQLTempNum(DEC_GameDay, DEC_GameTitleIDX, DEC_StadiumIDX,DEC_StadiumNumber, DEC_Searchkeyword,DEC_SearchKey,TempNum)
        
         CSQLTempNum = " EXEC tblGameTeamTourneyOrder_Searched_STR '" & DEC_GameLevelDtlIDX & "', '" & TeamGameNum & "', '" & TempNum & "'"
        'Response.Write "CSQLTempNum" & CSQLTempNum& "<br>"
        SET CRsTempNum = DBCon.Execute(CSQLTempNum)
        
        IF NOT (CRsTempNum.Eof and CRsTempNum.Bof) Then
          arrayGamePaperTempNum = CRsTempNum.getrows()
        End If
        CRsTempNum.close

        'Response.Write "IsArray(arrayGamePaperTempNum)" & IsArray(arrayGamePaperTempNum) & "<br>"

        arrayTempNumCnt = 0

        If IsArray(arrayGamePaperTempNum) Then
          For ar_TempNum = LBound(arrayGamePaperTempNum, 2) To UBound(arrayGamePaperTempNum, 2) 
            arrayTempNumCnt = arrayTempNumCnt + 1

            B_GameTitleIDX = arrayGamePaperTempNum(0, ar_TempNum) 
            B_GameLevelDtlIDX = arrayGamePaperTempNum(1, ar_TempNum) 
            B_TeamGameNum = arrayGamePaperTempNum(2, ar_TempNum) 
            B_GameNum = arrayGamePaperTempNum(3, ar_TempNum) 
            B_TeamGb = arrayGamePaperTempNum(4, ar_TempNum) 
            B_Level = arrayGamePaperTempNum(5, ar_TempNum) 
            B_LTourneyGroupIDX = arrayGamePaperTempNum(6, ar_TempNum) 
            B_RTourneyGroupIDX = arrayGamePaperTempNum(7, ar_TempNum) 
            B_TeamGbNM = arrayGamePaperTempNum(8, ar_TempNum) 
            B_LevelNM = arrayGamePaperTempNum(9, ar_TempNum) 
            B_PlayTypeNM = arrayGamePaperTempNum(10, ar_TempNum) 
            B_L_Result = arrayGamePaperTempNum(11, ar_TempNum) 
            B_L_ResultType = arrayGamePaperTempNum(12, ar_TempNum) 
            B_L_ResultNM = arrayGamePaperTempNum(13, ar_TempNum) 
            B_L_Jumsu = arrayGamePaperTempNum(14, ar_TempNum) 
            B_L_ResultDtl = arrayGamePaperTempNum(15, ar_TempNum) 
            B_R_Result = arrayGamePaperTempNum(16, ar_TempNum) 
            B_R_ResultType = arrayGamePaperTempNum(17, ar_TempNum) 
            B_R_ResultNM = arrayGamePaperTempNum(18, ar_TempNum) 
            B_R_Jumsu = arrayGamePaperTempNum(19, ar_TempNum) 
            B_R_ResultDtl = arrayGamePaperTempNum(20, ar_TempNum) 
            B_GameStatus = arrayGamePaperTempNum(21, ar_TempNum) 
            B_ROUNDS = arrayGamePaperTempNum(22, ar_TempNum) 
            B_Sex = arrayGamePaperTempNum(23, ar_TempNum) 
            B_TempNum = arrayGamePaperTempNum(24, ar_TempNum) 
            B_TurnNum = arrayGamePaperTempNum(25, ar_TempNum)
            B_GroupGameGb = arrayGamePaperTempNum(26, ar_TempNum) 
            B_TourneyCnt = arrayGamePaperTempNum(27, ar_TempNum) 
            'B_LTeamDtl = arrayGamePaperTempNum(28, ar) 
            'B_RTeamDtl = arrayGamePaperTempNum(29, ar) 
            B_LPlayer1 = arrayGamePaperTempNum(28, ar_TempNum) 
            B_LPlayer2 = arrayGamePaperTempNum(29, ar_TempNum) 
            B_Rplayer1 = arrayGamePaperTempNum(30, ar_TempNum) 
            B_Rplayer2 = arrayGamePaperTempNum(31, ar_TempNum) 
            B_LTeam1 = arrayGamePaperTempNum(32, ar_TempNum) 
            B_LTeam2 = arrayGamePaperTempNum(33, ar_TempNum) 
            B_RTeam1 = arrayGamePaperTempNum(34, ar_TempNum) 
            B_RTeam2 = arrayGamePaperTempNum(35, ar_TempNum) 
            B_StadiumNum = arrayGamePaperTempNum(36, ar_TempNum) 
            B_StadiumIDX = arrayGamePaperTempNum(37, ar_TempNum) 
            B_GameDay = arrayGamePaperTempNum(38, ar_TempNum) 
            B_LevelJooNum = arrayGamePaperTempNum(39, ar_TempNum) 
            B_LevelDtlJooNum = arrayGamePaperTempNum(40, ar_TempNum) 
            B_LevelDtlName = arrayGamePaperTempNum(41, ar_TempNum) 
            B_StadiumName = arrayGamePaperTempNum(42, ar_TempNum) 
            B_PlayLevelType = arrayGamePaperTempNum(43, ar_TempNum) 
            B_LevelJooName = arrayGamePaperTempNum(44, ar_TempNum) 
            B_Win_TourneyGroupIDX = arrayGamePaperTempNum(45, ar_TempNum) 
            B_LGroupJumsu = arrayGamePaperTempNum(46, ar_TempNum) 
            B_RGroupJumsu = arrayGamePaperTempNum(47, ar_TempNum) 
            B_LDtlJumsu = arrayGamePaperTempNum(48, ar_TempNum) 
            B_RDtlJumsu = arrayGamePaperTempNum(49, ar_TempNum) 
            B_SignData = arrayGamePaperTempNum(50, ar_TempNum) 
            B_MaxRound = arrayGamePaperTempNum(51, ar_TempNum) 
            B_GameType = arrayGamePaperTempNum(52, ar_TempNum) 
            B_GameTypeNM = arrayGamePaperTempNum(53, ar_TempNum)
            B_ResultGangSu = GetGangSu(B_GameType, B_MaxRound,B_ROUNDS) 


            IF cdbl(arrayTempNumCnt) = 1 Then
              Response.Write "<td class='column0 style16 s style11' colspan='5'>다음경기 "
              IF B_PlayLevelType = "B0100001" Then
                Response.Write "예선 " & B_LevelDtlJooNum & "조"
              ElseIf B_PlayLevelType = "B0100002" Then
                IF B_ResultGangSu = "" Then
                  Response.Write " 본선" 
                Else
                  Response.Write " 본선" & "-" & B_ResultGangSu
                ENd IF
              Else
                Response.Write "-"
              End If  
              Response.Write "(" & B_LPlayer1 & ", " & B_LPlayer2 & " / "  & B_RPlayer1 & ", " & B_RPlayer2 &  ")   ▷ " & B_StadiumNum & " 코트 " & B_TeamGameNum & "-" & B_GameNum & "</td>"

              Response.Write "<td class='column5 style7 null'></td>"
              Response.Write "<td class='column6 style1 null'></td>"
              Response.Write "<td class='column7 style1 null'></td>"
              Response.Write "<td class='column8 style1 null'></td>"
              Response.Write "<td class='column9 style1 null'></td>"
              Response.Write "<td class='column10'>&nbsp;</td>"
              Response.Write "<td class='column11'>&nbsp;</td>"
              Response.Write "<td class='column12'>&nbsp;</td>"
              Response.Write "<td class='column13'>&nbsp;</td>"
              Response.Write "</tr>"
              Response.Write "<tr class='row7'>"
              Response.Write "<tr class='row7'>"
            End IF

            IF cdbl(arrayTempNumCnt) = 2 Then
              Response.Write "<td class='column0 style16 s style11' colspan='5'>다음경기 "
              If B_PlayLevelType = "B0100001" Then
                Response.Write "예선 " & B_LevelDtlJooNum & "조"
              ElseIf B_PlayLevelType = "B0100002" Then
                    IF B_ResultGangSu = "" Then
                  Response.Write " 본선" 
                Else
                  Response.Write " 본선" & "-" & B_ResultGangSu
                ENd iF
              Else
                Response.Write "-"
              End If  
              Response.Write "(" & B_LPlayer1 & ", " & B_LPlayer2 & " / "  & B_RPlayer1 & ", " & B_RPlayer2 &  ")  ▷ " & B_StadiumNum & " 코트 "  & B_TeamGameNum & "-" & B_GameNum & "</td>"
            End IF
          NEXT
        END IF
      %>

      <!--<td class="column0 style16 s style11" colspan="5">다음경기 (이은수 / 이미경) -&gt; 12:30 ▷ 17코트 3경기 예정 (53)</td>-->
      <!--<td class="column0 style11 s style11" colspan="5">다음경기 (이동욱 / 김연옥) -&gt; 12:30 ▷ 16코트 3경기 예정 (52)</td>-->
      <td class="column5 style7 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row8">
      <td class="column0 style6 null"></td>
      <td class="column1 style6 null"></td>
      <td class="column2 style6 null"></td>
      <td class="column3 style6 null"></td>
      <td class="column4 style6 null"></td>
      <td class="column5 style8 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row9">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row10">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row11">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row12">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row13">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row14">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row15">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row16">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row17">
      <td class="column0 style1 null"></td>
      <td class="column1 style1 null"></td>
      <td class="column2 style1 null"></td>
      <td class="column3 style1 null"></td>
      <td class="column4 style1 null"></td>
      <td class="column5 style1 null"></td>
      <td class="column6 style1 null"></td>
      <td class="column7 style1 null"></td>
      <td class="column8 style1 null"></td>
      <td class="column9 style1 null"></td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row18">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row19">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row20">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row21">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row22">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row23">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
      <tr class="row24">
      <td class="column0">&nbsp;</td>
      <td class="column1">&nbsp;</td>
      <td class="column2">&nbsp;</td>
      <td class="column3">&nbsp;</td>
      <td class="column4">&nbsp;</td>
      <td class="column5">&nbsp;</td>
      <td class="column6">&nbsp;</td>
      <td class="column7">&nbsp;</td>
      <td class="column8">&nbsp;</td>
      <td class="column9">&nbsp;</td>
      <td class="column10">&nbsp;</td>
      <td class="column11">&nbsp;</td>
      <td class="column12">&nbsp;</td>
      <td class="column13">&nbsp;</td>
      </tr>
    </tbody>
  </table>
<%
    NEXT
  End If          
%>  
  </body>
</html>

<%
  DBClose()
%>
