<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html style="font-family: Calibri, Arial, Helvetica, sans-serif;font-size: 11pt;background-color: white;">
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <meta name="author" content="prettybora">
	  <meta name="company" content="LG">

  </head>

  <body style="left-margin: 0.2362204724409449in;right-margin: 0.2362204724409449in;top-margin: 0.7480314960629921in;bottom-margin: 0.7480314960629921in;">
<style>
@page { left-margin: 0.2362204724409449in; right-margin: 0.2362204724409449in; top-margin: 0.7480314960629921in; bottom-margin: 0.7480314960629921in; }
body { left-margin: 0.2362204724409449in; right-margin: 0.2362204724409449in; top-margin: 0.7480314960629921in; bottom-margin: 0.7480314960629921in; }
</style>
	<table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0" style="width: 1200px;border-collapse: collapse;page-break-after: always;">
		<col class="col0" style="width: 16.94444425pt;">
		</col><col class="col1" style="width: 16.94444425pt;">
		</col><col class="col2" style="width: 62pt;">
		</col><col class="col3" style="width: 62pt;">
		</col><col class="col4" style="width: 62pt;">
		</col><col class="col5" style="width: 62pt;">
		</col><col class="col6" style="width: 62pt;">
		</col><col class="col7" style="width: 62pt;">
		</col><col class="col8" style="width: 62pt;">
		</col><col class="col9" style="width: 62pt;">
		</col><col class="col10" style="width: 62pt;">
		</col><col class="col11" style="width: 62pt;">
		</col><col class="col12" style="width: 62pt;">
		</col><col class="col13" style="width: 62pt;">
		</col><col class="col14" style="width: 62pt;">
		</col><col class="col15" style="width: 62pt;">
		</col><col class="col16" style="width: 62pt;">
		</col><col class="col17" style="width: 62pt;">
		</col><tbody>
		  <tr class="row0" style="height: 21.2pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style24 null" style="vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #FF0000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;"></td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
			<td class="column7">&nbsp;</td>
			<td class="column8">&nbsp;</td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
			<td class="column12">&nbsp;</td>
			<td class="column13">&nbsp;</td>
			<td class="column14">&nbsp;</td>
			<td class="column15">&nbsp;</td>
			<td class="column16">&nbsp;</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row1" style="height: 21.2pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style37 null" style="vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #3F3F3F;font-family: '맑은 고딕';font-size: 16pt;background-color: white;"></td>
			<td class="column2 style42 s style42" colspan="9" style="text-align: left;vertical-align: middle;padding-left: 0px;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #3F3F3F;font-family: '맑은 고딕';font-size: 16pt;background-color: white;">남자 중등부</td>
			<td class="column11">&nbsp;</td>
			<td class="column12 style40 s" style="text-align: center;vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #3F3F3F;font-family: '맑은 고딕';font-size: 16pt;background-color: white;">No.1</td>
			<td class="column13">&nbsp;</td>
			<td class="column14 style37 s" style="text-align: left;vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #3F3F3F;font-family: '맑은 고딕';font-size: 16pt;background-color: white;">1코트</td>
			<td class="column15">&nbsp;</td>
			<td class="column16 style37 s" style="text-align: left;vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #3F3F3F;font-family: '맑은 고딕';font-size: 16pt;background-color: white;">1경기</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row2" style="height: 21.2pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style37 null" style="vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #3F3F3F;font-family: '맑은 고딕';font-size: 16pt;background-color: white;"></td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
			<td class="column7">&nbsp;</td>
			<td class="column8">&nbsp;</td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
			<td class="column12">&nbsp;</td>
			<td class="column13">&nbsp;</td>
			<td class="column14">&nbsp;</td>
			<td class="column15">&nbsp;</td>
			<td class="column16">&nbsp;</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row3" style="height: 21.2pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style30 null" style="vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #903C39;font-family: '맑은 고딕';font-size: 12pt;background-color: white;"></td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
			<td class="column7">&nbsp;</td>
			<td class="column8">&nbsp;</td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
			<td class="column12">&nbsp;</td>
			<td class="column13">&nbsp;</td>
			<td class="column14">&nbsp;</td>
			<td class="column15">&nbsp;</td>
			<td class="column16">&nbsp;</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row4" style="height: 30pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2 style61 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #FFFFFF;font-family: '맑은 고딕';font-size: 12pt;background-color: #27405E;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">소속</td>
			<td class="column3 style50 s style51" colspan="5" style="text-align: center;vertical-align: middle;border-left: none #000000;border-right: 2px solid #27405E !important;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 12pt;background-color: white;border-bottom: 2px solid #27405E !important;border-top: 2px solid #27405E !important;">서울B</td>
			<td class="column8 style25 null" style="vertical-align: middle;text-align: center;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 12pt;background-color: white;"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11 style49 s style50" colspan="5" style="text-align: center;vertical-align: middle;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 12pt;background-color: white;border-left: 2px solid #27405E !important;border-bottom: 2px solid #27405E !important;border-top: 2px solid #27405E !important;">제주</td>
			<td class="column16 style61 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #FFFFFF;font-family: '맑은 고딕';font-size: 12pt;background-color: #27405E;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">소속</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row5" style="height: 9.949999999999999pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
			<td class="column7">&nbsp;</td>
			<td class="column8">&nbsp;</td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
			<td class="column12">&nbsp;</td>
			<td class="column13">&nbsp;</td>
			<td class="column14">&nbsp;</td>
			<td class="column15">&nbsp;</td>
			<td class="column16">&nbsp;</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row6" style="height: 21.2pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style59 s style60" rowspan="2" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 1px solid #000000 !important;">No</td>
			<td class="column2 style45 s style47" colspan="2" rowspan="2" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;">선수명</td>
			<td class="column4 style54 s style56" colspan="5" style="text-align: center;vertical-align: middle;border-right: 2px solid #000000 !important;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-left: 1px solid #000000 !important;border-bottom: 1px solid #000000 !important;border-top: 2px solid #000000 !important;">결과</td>
			<td class="column9 style52 s style53" rowspan="2" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">종목</td>
			<td class="column10 style57 s style58" colspan="5" style="text-align: center;vertical-align: middle;border-right: 1px solid #000000 !important;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-left: 2px solid #000000 !important;border-bottom: 1px solid #000000 !important;border-top: 2px solid #000000 !important;">결과</td>
			<td class="column15 style45 s style48" colspan="2" rowspan="2" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 2px solid #000000 !important;">선수명</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row7" style="height: 21.2pt;">
			<td class="column0">&nbsp;</td>
			<td class="column4 style16 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;">3게임</td>
			<td class="column5 style16 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;">2게임</td>
			<td class="column6 style16 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;">1게임</td>
			<td class="column7 style17 s" style="text-align: center;vertical-align: middle;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;">승/패</td>
			<td class="column8 style17 s" style="text-align: center;vertical-align: middle;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;">승자서명</td>
			<td class="column10 style26 s" style="text-align: center;vertical-align: middle;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;">승자서명</td>
			<td class="column11 style16 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;">승/패</td>
			<td class="column12 style39 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;">1게임</td>
			<td class="column13 style39 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;">2게임</td>
			<td class="column14 style39 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;">3게임</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row8" style="height: 35pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style12 n" style="text-align: center;vertical-align: middle;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 1px solid #000000 !important;">1</td>
			<td class="column2 style13 null" style="vertical-align: middle;text-align: center;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column3 style13 null" style="vertical-align: middle;text-align: center;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column4 style14 null" style="vertical-align: middle;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column5 style14 null" style="vertical-align: middle;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column6 style14 null" style="vertical-align: middle;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column7 style18 null" style="vertical-align: middle;border-top: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column8 style18 null" style="vertical-align: middle;border-top: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column9 style21 s" style="text-align: center;vertical-align: middle;border-top: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">단식</td>
			<td class="column10 style28 null" style="vertical-align: middle;text-align: center;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;"></td>
			<td class="column11 style14 null" style="vertical-align: middle;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column12 style14 null" style="vertical-align: middle;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column13 style14 null" style="vertical-align: middle;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column14 style14 null" style="vertical-align: middle;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column15 style13 null" style="vertical-align: middle;text-align: center;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column16 style15 null" style="vertical-align: middle;text-align: center;border-top: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 2px solid #000000 !important;"></td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row9" style="height: 35pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style6 n" style="text-align: center;vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 1px solid #000000 !important;">2</td>
			<td class="column2 style4 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column3 style4 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column4 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column5 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column6 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column7 style19 null" style="vertical-align: middle;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column8 style19 null" style="vertical-align: middle;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column9 style22 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">단식</td>
			<td class="column10 style27 null" style="vertical-align: middle;text-align: center;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;"></td>
			<td class="column11 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column12 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column13 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column14 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column15 style4 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column16 style7 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 2px solid #000000 !important;"></td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row10" style="height: 35pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style6 n" style="text-align: center;vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 1px solid #000000 !important;">3</td>
			<td class="column2 style4 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column3 style4 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column4 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column5 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column6 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column7 style19 null" style="vertical-align: middle;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column8 style19 null" style="vertical-align: middle;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column9 style22 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">복식</td>
			<td class="column10 style27 null" style="vertical-align: middle;text-align: center;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;"></td>
			<td class="column11 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column12 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column13 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column14 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column15 style4 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column16 style7 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 2px solid #000000 !important;"></td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row11" style="height: 35pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style6 n" style="text-align: center;vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 1px solid #000000 !important;">4</td>
			<td class="column2 style4 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column3 style4 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column4 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column5 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column6 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column7 style19 null" style="vertical-align: middle;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column8 style19 null" style="vertical-align: middle;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column9 style22 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">복식</td>
			<td class="column10 style27 null" style="vertical-align: middle;text-align: center;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;"></td>
			<td class="column11 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column12 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column13 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column14 style5 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column15 style4 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column16 style7 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 1px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 2px solid #000000 !important;"></td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row12" style="height: 35pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style8 n" style="text-align: center;vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 1px solid #000000 !important;">5</td>
			<td class="column2 style9 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column3 style9 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column4 style10 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column5 style10 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column6 style10 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column7 style20 null" style="vertical-align: middle;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column8 style20 null" style="vertical-align: middle;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;"></td>
			<td class="column9 style23 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">단식</td>
			<td class="column10 style26 null" style="vertical-align: middle;text-align: center;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;"></td>
			<td class="column11 style10 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column12 style10 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column13 style10 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column14 style10 null" style="vertical-align: middle;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column15 style9 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 1px solid #000000 !important;"></td>
			<td class="column16 style11 null" style="vertical-align: middle;text-align: center;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 1px solid #000000 !important;border-left: 1px solid #000000 !important;border-right: 2px solid #000000 !important;"></td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row13" style="height: 42pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4 style34 s" style="text-align: center;vertical-align: middle;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: #F2F2F2;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;">&nbsp;-</td>
			<td class="column5 style34 s" style="text-align: center;vertical-align: middle;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: #F2F2F2;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;">&nbsp;-</td>
			<td class="column6 style34 s" style="text-align: center;vertical-align: middle;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: #F2F2F2;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;">&nbsp;-</td>
			<td class="column7 style32 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">승자팀<br>
체크</td>
			<td class="column8 style31 null" style="vertical-align: middle;border-left: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-right: 2px solid #000000 !important;"></td>
			<td class="column9 style29 s" style="text-align: center;vertical-align: middle;border-top: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">총점<br>
합계</td>
			<td class="column10 style33 null" style="vertical-align: middle;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;"></td>
			<td class="column11 style32 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: white;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">승자팀<br>
체크</td>
			<td class="column12 style34 s" style="text-align: center;vertical-align: middle;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: #F2F2F2;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;">&nbsp;-</td>
			<td class="column13 style34 s" style="text-align: center;vertical-align: middle;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: #F2F2F2;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;">&nbsp;-</td>
			<td class="column14 style38 s" style="text-align: center;vertical-align: middle;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 10pt;background-color: #F2F2F2;border-bottom: 2px solid #000000 !important;border-top: 2px solid #000000 !important;border-left: 2px solid #000000 !important;border-right: 2px solid #000000 !important;">&nbsp;-</td>
			<td class="column15">&nbsp;</td>
			<td class="column16">&nbsp;</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row14" style="height: 21.2pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
			<td class="column7">&nbsp;</td>
			<td class="column8">&nbsp;</td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
			<td class="column12">&nbsp;</td>
			<td class="column13">&nbsp;</td>
			<td class="column14">&nbsp;</td>
			<td class="column15">&nbsp;</td>
			<td class="column16">&nbsp;</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row15" style="height: 21.2pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
			<td class="column7">&nbsp;</td>
			<td class="column8">&nbsp;</td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
			<td class="column12">&nbsp;</td>
			<td class="column13">&nbsp;</td>
			<td class="column14">&nbsp;</td>
			<td class="column15">&nbsp;</td>
			<td class="column16">&nbsp;</td>
			<td class="column17">&nbsp;</td>
		  </tr>
		  <tr class="row16" style="height: 21.2pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column2 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column3 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column4 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column5 style43 s style43" colspan="2" style="text-align: center;vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 14pt;background-color: white;border-bottom: 2px solid #000000 !important;">Umpire :</td>
			<td class="column7 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column8 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column9 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column10 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column11 style43 s style43" colspan="3" style="text-align: center;vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 14pt;background-color: white;border-bottom: 2px solid #000000 !important;">Referee:</td>
			<td class="column14 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column15 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column16 style41 null" style="vertical-align: middle;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;border-bottom: 2px solid #000000 !important;"></td>
			<td class="column17 style36 null" style="vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;color: #000000;font-family: '맑은 고딕';font-size: 11pt;background-color: white;"></td>
		  </tr>
		  <tr class="row17" style="height: 54pt;">
			<td class="column0">&nbsp;</td>
			<td class="column1 style44 s style44" colspan="16" style="text-align: center;vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 24pt;background-color: white;">BADMINTON KOREA ASSOCIATION</td>
			<td class="column17 style35 null" style="vertical-align: middle;border-bottom: none #000000;border-top: none #000000;border-left: none #000000;border-right: none #000000;font-weight: bold;color: #000000;font-family: '맑은 고딕';font-size: 36pt;background-color: white;"></td>
		  </tr>
		</tbody>
	</table>
  </body>
</html>


<%
  'Response.END
  Response.Buffer = True
  Response.ContentType = "application/vnd.ms-excel"
  Response.CacheControl = "public"
  Response.AddHeader "Content-disposition","attachment;filename=score.xls"
%>
