<% 
strConnect = strConnect&"Provider=SQLOLEDB.1;Persist Security Info=True;"
'strConnect = strConnect&"Data Source=115.68.7.143;"  
strConnect = strConnect&"Data Source=db.itemcenter.co.kr;"  
'strConnect = strConnect&"User ID=rubin;"             
'strConnect = strConnect&"Password=ic@04#1058;"             
strConnect = strConnect&"User ID=widsql;"             
strConnect = strConnect&"Password=ic%^&1058!@#;"             

strConnect = strConnect&"Initial Catalog=ITEMCENTER;"   
%>